# Generated by Django 5.2.17 on 2026-09-14 07:21

import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import (
    DROP_SYSTEM_ROW_LOCK_FUNCTION,
    SYSTEM_ROW_LOCK_FUNCTION,
    disable_rls,
    drop_lock_system_rows,
    enable_rls_shared,
    lock_system_rows,
)


class Migration(migrations.Migration):
    """``leave_type`` — the second shared-tenancy table, and it arrives in P4.

    Shared rather than optional: a NULL ``tenant_id`` means *every employer may
    read this*, which is the opposite of what the same NULL means under
    ``enable_rls_optional``. Same shape as ``payroll_component`` (D-87), and the
    system-row lock is here for the same reason — DELETE is checked against USING
    only, so without the trigger a tenant that can see a statutory leave type can
    delete it out from under every other employer (D-93).

    Out of phase deliberately: ``employee_leave_entitlement`` is a P4 table and
    cannot point at a table that does not exist (D-127).
    """


    initial = True

    dependencies = [
        ("core", "0004_audit_read_operation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=100)),
                (
                    "balance_source",
                    models.CharField(
                        choices=[
                            ("own", "Keeps its own balance"),
                            ("parent", "Consumes the parent type's balance"),
                            ("none", "Has no balance at all"),
                        ],
                        default="own",
                        max_length=30,
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                ("is_statutory", models.BooleanField(default=True)),
                (
                    "accrues",
                    models.BooleanField(
                        default=True,
                        help_text="FALSE for unpaid and unauthorised leave.",
                    ),
                ),
                (
                    "cycle_months",
                    models.SmallIntegerField(
                        default=12,
                        help_text="12 for annual and family responsibility, 36 for sick.",
                    ),
                ),
                ("requires_evidence", models.BooleanField(default=False)),
                (
                    "payable_on_termination",
                    models.BooleanField(
                        default=False,
                        help_text="TRUE only for annual leave — BCEA s40(b).",
                    ),
                ),
                (
                    "reduces_pay_when_exhausted",
                    models.BooleanField(
                        default=True,
                        help_text="Converts to unpaid once the balance is zero.",
                    ),
                ),
                (
                    "counts_as_service",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the period counts toward service length.",
                    ),
                ),
                ("colour_hex", models.CharField(default="#4A7C9E", max_length=7)),
                ("display_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_leave_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lets a sub-type draw on a parent balance.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_types",
                        to="leave.leavetype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_type",
                "ordering": ["display_order", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.comparison.Coalesce(
                            "tenant_id", models.Value(0)
                        ),
                        models.F("code"),
                        name="uniq_leave_type_code_per_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("balance_source__in", ["own", "parent", "none"])
                        ),
                        name="leave_type_balance_source_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cycle_months__gt", 0)),
                        name="leave_type_cycle_is_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("balance_source", "parent"), _negated=True),
                            ("parent_leave_type__isnull", False),
                            _connector="OR",
                        ),
                        name="leave_type_parent_balance_needs_a_parent",
                    ),
                ],
            },
        ),
        migrations.RunSQL(SYSTEM_ROW_LOCK_FUNCTION, DROP_SYSTEM_ROW_LOCK_FUNCTION),
        migrations.RunSQL(enable_rls_shared("leave_type"), disable_rls("leave_type")),
        migrations.RunSQL(lock_system_rows("leave_type"), drop_lock_system_rows("leave_type")),
    ]
