# Originally generated by Django 5.2.17 on 2026-09-14 08:26

from django.conf import settings
"""The column the system-row lock has been keying on since it was installed.

``0001`` created ``leave_type``, enabled the shared policy and installed
``lock_system_rows("leave_type")`` — a trigger whose first statement is
``IF NOT OLD.is_system``. The column was never added. So every UPDATE and every
DELETE on any row of this table, a tenant's own included, failed inside the
trigger with ``record "old" has no field "is_system"``: an employer could add
"Birthday leave" and then never rename or remove it.

It went unseen because the one test that exercised the area asserted
``DatabaseError`` and the missing-field error is one — the test passed on the
wrong exception. Tests here now assert on the message too.

The two CHECKs are the pair ``payroll_component`` already carries: a shared row IS
a system row, and a tenant's row never is. Without the first, a shared row with
``is_system`` false is readable by every tenant and deletable by any of them,
because a DELETE is checked against the policy's USING clause only (D-93).
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tenantmembership_ui_preferences"),
        ("leave", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="System types cannot be edited or deleted (D-93).",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tenant__isnull", False), ("is_system", True), _connector="OR"
                ),
                name="leave_type_shared_rows_are_system_rows",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tenant__isnull", True), ("is_system", False), _connector="OR"
                ),
                name="leave_type_system_rows_are_shared_rows",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.CheckConstraint(
                condition=models.Q(("colour_hex__regex", "^#[0-9A-Fa-f]{6}$")),
                name="leave_type_colour_is_a_hex_triplet",
            ),
        ),
    ]
