# Generated by Django 5.2.17 on 2026-09-15 08:18

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import statutory.models
from django.conf import settings
from django.db import migrations, models

from core.db.rls import append_only, drop_append_only


class Migration(migrations.Migration):
    """P6 chunk 1: leave_cycle, leave_transaction and leave_accrual_run.

    ``leave_transaction`` is append-only by TRIGGER
    (``core/db/rls.py::append_only()``) — invariant 3 lives here, and P0
    already learned that a ``REVOKE`` does not bind the table owner the
    application connects as. ``APPEND_ONLY_FUNCTION`` was created once, in
    ``core/migrations/0001_initial.py``; this migration only attaches the
    trigger to this table.

    ``leave_cycle``'s ``EXCLUDE`` constraint needs ``btree_gist``, already
    installed by ``statutory/migrations/0002`` — no extension operation
    needed here.
    """

    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0008_employeeimportbatch_employee_created_by_import_batch_and_more"),
        ("employers", "0004_payroll_component"),
        ("leave", "0002_leave_type_system_rows"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle_number",
                    models.SmallIntegerField(
                        default=1, help_text="1, 2, 3... from the engagement's own start date."
                    ),
                ),
                ("cycle_start", models.DateField(db_index=True)),
                ("cycle_end", models.DateField(db_index=True, help_text="Exclusive.")),
                (
                    "unit",
                    models.CharField(choices=[("days", "Days"), ("hours", "Hours")], max_length=10),
                ),
                (
                    "entitlement_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Full-cycle entitlement, statutory + contractual, in `unit`.",
                        max_digits=8,
                    ),
                ),
                (
                    "accrued_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                ("taken_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                (
                    "paid_out_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "adjusted_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Manual corrections, signed.",
                        max_digits=8,
                    ),
                ),
                (
                    "carried_in_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Brought forward from the prior cycle.",
                        max_digits=8,
                    ),
                ),
                (
                    "forfeited_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Zero until an employer captures a forfeiture by hand (D-D). Never automatic.",
                        max_digits=8,
                    ),
                ),
                (
                    "balance_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Derived: carried_in + accrued + adjusted - taken - paid_out - forfeited.",
                        max_digits=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("forfeited", "Forfeited"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "is_stale",
                    models.BooleanField(
                        default=False,
                        help_text="Set when a leave_transaction against this cycle changes.",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_cycles",
                        to="employees.employee",
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_cycles",
                        to="employees.employeeengagement",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cycles",
                        to="leave.leavetype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_cycle",
                "ordering": ["employee_id", "leave_type_id", "cycle_number"],
            },
        ),
        migrations.CreateModel(
            name="LeaveTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField(db_index=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("accrual", "Accrual"),
                            ("opening_balance", "Opening balance"),
                            ("taken", "Taken"),
                            ("payout", "Payout"),
                            ("forfeiture", "Forfeiture"),
                            ("adjustment", "Adjustment"),
                            ("reversal", "Reversal"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Signed. See the model docstring's sign convention.",
                        max_digits=8,
                    ),
                ),
                (
                    "unit",
                    models.CharField(choices=[("days", "Days"), ("hours", "Hours")], max_length=10),
                ),
                (
                    "leave_application_id_ref",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Becomes a real FK to leave_application in chunk 2.",
                        null=True,
                    ),
                ),
                (
                    "payroll_run_id_ref",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Becomes a real FK to payroll_run in P7. Set for a payout processed in a run.",
                        null=True,
                    ),
                ),
                (
                    "calculation_basis",
                    models.CharField(
                        blank=True,
                        help_text="monthly_1_25 | monthly_1_50 | per_17_days | per_17_hours | per_26_days_first_6m | manual",
                        max_length=40,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, help_text="Mandatory for adjustments.", max_length=255
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_transactions",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="leave.leavecycle",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="leave.leavetype",
                    ),
                ),
                (
                    "reverses_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only on a reversal — the row it corrects.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="leave.leavetransaction",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_transaction",
                "ordering": ["-transaction_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LeaveAccrualRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accrual_as_at", models.DateField(db_index=True, help_text="Usually month end.")),
                ("employees_processed", models.IntegerField(default=0)),
                ("transactions_created", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_detail", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_accrual_runs",
                        to="employers.employer",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accrual_runs",
                        to="leave.leavetype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_accrual_run",
                "ordering": ["-accrual_as_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employer", "leave_type", "accrual_as_at"),
                        name="uniq_leave_accrual_run_per_employer_type_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["pending", "running", "completed", "failed"])
                        ),
                        name="leave_accrual_run_status_is_known",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="leavecycle",
            index=models.Index(
                fields=["tenant", "leave_type", "status"], name="leave_cycle_tenant__393876_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leavecycle",
            index=models.Index(fields=["cycle_end"], name="leave_cycle_cycle_e_195ee2_idx"),
        ),
        migrations.AddConstraint(
            model_name="leavecycle",
            constraint=models.UniqueConstraint(
                fields=("employee", "leave_type", "cycle_number"),
                name="uniq_leave_cycle_number_per_employee_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavecycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("cycle_end__gt", models.F("cycle_start"))),
                name="leave_cycle_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavecycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit__in", ["days", "hours"])),
                name="leave_cycle_unit_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavecycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "closed", "forfeited"])),
                name="leave_cycle_status_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavecycle",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        statutory.models.DateRange(
                            "cycle_start",
                            "cycle_end",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("employee", "="),
                    ("leave_type", "="),
                ],
                name="leave_cycle_no_overlapping_periods",
            ),
        ),
        migrations.AddIndex(
            model_name="leavetransaction",
            index=models.Index(
                fields=["employee", "leave_type", "transaction_date"],
                name="leave_trans_employe_d90812_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leavetransaction",
            index=models.Index(
                fields=["tenant", "transaction_type"], name="leave_trans_tenant__9b837c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "transaction_type__in",
                        [
                            "accrual",
                            "opening_balance",
                            "taken",
                            "payout",
                            "forfeiture",
                            "adjustment",
                            "reversal",
                        ],
                    )
                ),
                name="leave_transaction_type_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit__in", ["days", "hours"])),
                name="leave_transaction_unit_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("quantity__gt", 0), ("transaction_type", "accrual")),
                    models.Q(("quantity__gt", 0), ("transaction_type", "opening_balance")),
                    models.Q(("quantity__lt", 0), ("transaction_type", "taken")),
                    models.Q(("quantity__lt", 0), ("transaction_type", "payout")),
                    models.Q(("quantity__lt", 0), ("transaction_type", "forfeiture")),
                    ("transaction_type", "adjustment"),
                    ("transaction_type", "reversal"),
                    _connector="OR",
                ),
                name="leave_transaction_sign_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("transaction_type", "adjustment"), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="leave_transaction_adjustment_states_a_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reverses_transaction__isnull", False), ("transaction_type", "reversal")
                    ),
                    models.Q(
                        models.Q(("transaction_type", "reversal"), _negated=True),
                        ("reverses_transaction__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="leave_transaction_reversal_names_what_it_reverses",
            ),
        ),
        migrations.RunSQL(append_only("leave_transaction"), drop_append_only("leave_transaction")),
    ]
