# Generated by Django 5.2.17 on 2026-09-15 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Corrects 0003's uniqueness to the engagement, not the employee (D-B).

    0003 was generated before ``leave/models.py`` was edited to deviate from
    sheet 02's own ``(employee, leave_type, cycle_number)`` shape — the model
    file changed, the migration that created the table never did, and the
    mismatch went unnoticed because nothing had yet run a re-hire through it.
    A bare ``(employee, leave_type, cycle_number)`` unique collides the
    moment a re-hire's fresh cycle 1 tries to exist alongside the original
    engagement's own cycle 1, which is exactly the case decision B exists to
    make work. Scoping to the engagement instead is what "a re-hire starts
    fresh cycles" actually requires at the database level, not only in the
    service function that generates them.

    Also carries the ``balance_quantity`` help_text correction: it named the
    workbook's own subtraction formula, which double-counts once
    ``taken``/``paid_out``/``forfeited`` are stored NEGATIVE per
    ``leave_transaction``'s sign convention — ``leave/balances.py`` always
    computed the correct sum; only the column's own description was stale.
    """

    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0008_employeeimportbatch_employee_created_by_import_batch_and_more"),
        ("leave", "0003_leave_cycle_and_transaction_ledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="leavecycle",
            name="uniq_leave_cycle_number_per_employee_type",
        ),
        migrations.AlterField(
            model_name="leavecycle",
            name="balance_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Derived: the SUM of carried_in, accrued, adjusted, taken, paid_out and forfeited — a plain addition, not a subtraction, because taken, paid_out and forfeited are themselves stored NEGATIVE per leave_transaction's own sign convention. Subtracting a negative would double the effect.",
                max_digits=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="leavecycle",
            constraint=models.UniqueConstraint(
                fields=("engagement", "leave_type", "cycle_number"),
                name="uniq_leave_cycle_number_per_engagement_type",
            ),
        ),
    ]
