# Generated by Django 5.2.17 on 2026-09-15 11:05

from django.db import migrations

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """0003 created three TenantScopedModel tables and enabled RLS on none of
    them — every ``ENABLE ROW LEVEL SECURITY`` and ``CREATE POLICY`` call was
    simply missing, and nothing in that migration's own review caught it,
    because a table with RLS enabled and NO policy denies every row rather
    than exposing any of them: every test written against these tables so far
    ran inside a pinned tenant context and read back exactly the row it had
    just written, which is indistinguishable from correct isolation unless a
    SECOND tenant is put in the room. The generated isolation suite is what
    actually caught it — ``test_policy_exists`` failed the moment these three
    models were exercised by it for the first time, which is the whole reason
    that suite is generated from the model registry rather than written by
    hand per table (CLAUDE.md's non-negotiable #1).

    ``leave_transaction`` already got its append-only trigger in 0003; this
    migration is additive to that, not a replacement for it.
    """

    dependencies = [
        ("leave", "0004_leave_cycle_engagement_scoped_uniqueness"),
    ]

    operations = [
        migrations.RunSQL(enable_rls("leave_cycle"), disable_rls("leave_cycle")),
        migrations.RunSQL(enable_rls("leave_transaction"), disable_rls("leave_transaction")),
        migrations.RunSQL(enable_rls("leave_accrual_run"), disable_rls("leave_accrual_run")),
    ]
