# Generated by Django 5.2.17 on 2026-09-15 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """P6 chunk 2, task 0: reconciles leave_transaction against sheet 02 (D-170).

    Sheet 02 names ``days`` NOT NULL and ``hours`` nullable. Read literally,
    every row would need a DAYS figure, which for an hourly-accrual employee
    can only come from converting hours into a days-equivalent against the
    employee's own work schedule — exactly the silent, lossy conversion
    D-164 (decision C, chunk 1) exists to prevent. Kept BOTH columns
    NULLABLE instead, with a CHECK proving exactly one is ever populated:
    the workbook's own column names, chunk 1's own data shape (one unit,
    never converted, never both). See the model docstring and D-170.

    Replaces chunk 1's single ``quantity`` + ``unit`` pair. No data
    migration needed — this table has never carried a real row outside a
    test database.
    """

    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0008_employeeimportbatch_employee_created_by_import_batch_and_more"),
        ("leave", "0005_enable_rls_on_cycle_transaction_and_accrual_run"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="leavetransaction",
            name="leave_transaction_unit_is_known",
        ),
        migrations.RemoveConstraint(
            model_name="leavetransaction",
            name="leave_transaction_sign_matches_type",
        ),
        migrations.RemoveField(
            model_name="leavetransaction",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="leavetransaction",
            name="unit",
        ),
        migrations.AddField(
            model_name="leavetransaction",
            name="days",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Signed. Populated when this row's own unit is DAYS. See the model docstring's sign convention and D-170's reconciliation against sheet 02.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leavetransaction",
            name="hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Signed. Populated when this row's own unit is HOURS (D-170). Never both.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("days__isnull", False), ("hours__isnull", True)),
                    models.Q(("days__isnull", True), ("hours__isnull", False)),
                    _connector="OR",
                ),
                name="leave_transaction_exactly_one_of_days_or_hours",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("days__gt", 0), ("days__isnull", False), ("transaction_type", "accrual")
                    ),
                    models.Q(
                        ("hours__gt", 0), ("hours__isnull", False), ("transaction_type", "accrual")
                    ),
                    models.Q(
                        ("days__gt", 0),
                        ("days__isnull", False),
                        ("transaction_type", "opening_balance"),
                    ),
                    models.Q(
                        ("hours__gt", 0),
                        ("hours__isnull", False),
                        ("transaction_type", "opening_balance"),
                    ),
                    models.Q(
                        ("days__isnull", False), ("days__lt", 0), ("transaction_type", "taken")
                    ),
                    models.Q(
                        ("hours__isnull", False), ("hours__lt", 0), ("transaction_type", "taken")
                    ),
                    models.Q(
                        ("days__isnull", False), ("days__lt", 0), ("transaction_type", "payout")
                    ),
                    models.Q(
                        ("hours__isnull", False), ("hours__lt", 0), ("transaction_type", "payout")
                    ),
                    models.Q(
                        ("days__isnull", False), ("days__lt", 0), ("transaction_type", "forfeiture")
                    ),
                    models.Q(
                        ("hours__isnull", False),
                        ("hours__lt", 0),
                        ("transaction_type", "forfeiture"),
                    ),
                    ("transaction_type", "adjustment"),
                    ("transaction_type", "reversal"),
                    _connector="OR",
                ),
                name="leave_transaction_sign_matches_type",
            ),
        ),
    ]
