# Generated by Django 5.2.17 on 2026-09-15 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import drop_no_delete, no_delete


class Migration(migrations.Migration):
    """P6 chunk 2, task 1: the sick-leave evidence catalogue.

    No tenant field, no RLS — this is pure reference data, the same shape as
    ``sector`` or ``bank`` (see the model docstring). ``no_delete()`` guards
    it regardless, because ``leave_application`` (a ``TenantScopedModel``
    under FORCE ROW LEVEL SECURITY, arriving in this same chunk) will point
    at it, and D-76 already found what happens when a reference table has no
    such trigger: a session with no tenant pinned deletes the row, the
    referencing table's own RLS hides the rows that should have protected
    it, and neither Django's ``PROTECT`` nor PostgreSQL's own FK check
    raises. ``NO_DELETE_FUNCTION`` was created once already, in
    ``statutory/migrations/0008``; this migration only attaches the trigger.
    """

    dependencies = [
        ("leave", "0006_reconcile_leave_transaction_days_hours"),
        ("statutory", "0008_reference_tables_refuse_deletes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveEvidenceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("DOCTOR_NOTE", "Doctor's note"),
                            ("CLINIC_NOTE", "Clinic note"),
                            ("NO_NOTE", "No note produced"),
                            ("SELF_CERTIFIED", "Self-certified"),
                        ],
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("requires_attachment", models.BooleanField(default=False)),
                (
                    "is_paid_by_default",
                    models.BooleanField(
                        default=True,
                        help_text="BCEA s23 allows pay to be withheld without a certificate in defined cases.",
                    ),
                ),
                (
                    "max_consecutive_days_without_note",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="BCEA s23(1): beyond this many consecutive days with no certificate, pay may be withheld. Read from SICK_CERTIFICATE_MAX_CONSECUTIVE_DAYS via statutory.resolve, never invented here. NULL where the variant already carries its own proof and the threshold does not apply.",
                        null=True,
                    ),
                ),
                ("display_order", models.SmallIntegerField(default=0)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_types",
                        to="leave.leavetype",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_evidence_type",
                "ordering": ["leave_type_id", "display_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("leave_type", "code"),
                        name="uniq_leave_evidence_type_per_leave_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "code__in",
                                ["DOCTOR_NOTE", "CLINIC_NOTE", "NO_NOTE", "SELF_CERTIFIED"],
                            )
                        ),
                        name="leave_evidence_type_code_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_consecutive_days_without_note__isnull", True),
                            ("max_consecutive_days_without_note__gt", 0),
                            _connector="OR",
                        ),
                        name="leave_evidence_type_threshold_is_positive",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            no_delete("leave_evidence_type"), drop_no_delete("leave_evidence_type")
        ),
    ]
