# Generated by Django 5.2.17 on 2026-09-15 12:51

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import statutory.models
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """P6 chunk 2, task 2: leave_application and leave_application_day.

    Both TenantScopedModel — RLS is enabled for both in THIS migration,
    unlike chunk 1's ``leave_cycle``/``leave_transaction``/``leave_accrual_run``
    (D-169), which shipped without it and were only caught by the generated
    isolation suite afterward. Not repeating that omission here.
    """

    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0008_employeeimportbatch_employee_created_by_import_batch_and_more"),
        ("leave", "0007_leave_evidence_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        help_text="Human reference, e.g. LV-2026-00042.", max_length=20
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                (
                    "total_days",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Working days only, from the work schedule.",
                        max_digits=7,
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                ("is_part_day", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("taken", "Taken"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_comment", models.CharField(blank=True, max_length=500)),
                (
                    "balance_at_submission",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Snapshot for the audit trail.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "exceeds_balance",
                    models.BooleanField(
                        default=False, help_text="Overdrawn days fall to unpaid unless overridden."
                    ),
                ),
                (
                    "unpaid_days",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Portion that will be unpaid.",
                        max_digits=7,
                    ),
                ),
                ("cancelled_reason", models.CharField(blank=True, max_length=255)),
                (
                    "self_approved",
                    models.BooleanField(
                        default=False,
                        help_text="TRUE only where the owner is also the applicant and no other approver exists.",
                    ),
                ),
                (
                    "self_approval_reason",
                    models.CharField(
                        blank=True,
                        help_text="Mandatory when self_approved — visible in the leave register, never hidden.",
                        max_length=255,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="The employer authorisation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_applications",
                        to="employees.employee",
                    ),
                ),
                (
                    "evidence_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Medical certificate.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fileobject",
                    ),
                ),
                (
                    "leave_evidence_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which of the four sick-leave variants, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="leave.leaveevidencetype",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="leave.leavetype",
                    ),
                ),
                (
                    "submitted_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_application",
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApplicationDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("leave_date", models.DateField(db_index=True)),
                (
                    "day_portion",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="1.000 full day, 0.500 half day.",
                        max_digits=4,
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                (
                    "is_working_day",
                    models.BooleanField(
                        default=True,
                        help_text="FALSE for rest days and public holidays — not deducted.",
                    ),
                ),
                ("is_public_holiday", models.BooleanField(default=False)),
                (
                    "is_paid",
                    models.BooleanField(
                        default=True,
                        help_text="FALSE where the balance is exhausted or evidence withholds pay.",
                    ),
                ),
                ("deducted_from_balance", models.BooleanField(default=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="leave.leaveapplication",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_application_day",
                "ordering": ["leave_application_id", "leave_date"],
            },
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["employee", "start_date"], name="leave_appli_employe_29a255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(fields=["tenant", "status"], name="leave_appli_tenant__92ca80_idx"),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["start_date", "end_date"], name="leave_appli_start_d_c52a8a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveapplication",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reference"), name="uniq_leave_application_reference"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="leave_application_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "submitted", "approved", "declined", "cancelled", "taken"],
                    )
                ),
                name="leave_application_status_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    ("decided_by_user__isnull", False),
                    _connector="OR",
                ),
                name="leave_application_approval_names_the_approver",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("self_approved", True), _negated=True),
                    models.Q(("self_approval_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="leave_application_self_approval_states_a_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveapplication",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", "approved")),
                expressions=[
                    (
                        statutory.models.DateRange(
                            "start_date",
                            "end_date",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                    ("employee", "="),
                ],
                name="leave_application_no_overlapping_approved",
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapplicationday",
            index=models.Index(
                fields=["tenant", "leave_date"], name="leave_appli_tenant__d73f64_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveapplicationday",
            constraint=models.UniqueConstraint(
                fields=("leave_application", "leave_date"),
                name="uniq_leave_application_day_per_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveapplicationday",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_portion__gt", 0), ("day_portion__lte", 1)),
                name="leave_application_day_portion_in_range",
            ),
        ),
        migrations.RunSQL(enable_rls("leave_application"), disable_rls("leave_application")),
        migrations.RunSQL(
            enable_rls("leave_application_day"), disable_rls("leave_application_day")
        ),
    ]
