# Generated by Django 5.2.17 on 2026-09-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Completes task 0's reconciliation: leave_transaction.leave_application
    is now a real FK, since leave_application exists as of 0008. No data
    migration — the placeholder was never set by anything before this chunk.
    """

    dependencies = [
        ("leave", "0008_leave_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavetransaction",
            name="leave_application_id_ref",
        ),
        migrations.AddField(
            model_name="leavetransaction",
            name="leave_application",
            field=models.ForeignKey(
                blank=True,
                help_text="Set by leave/authorisation.py's approve() and reverse_transaction() on cancel.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leave_transactions",
                to="leave.leaveapplication",
            ),
        ),
    ]
