# Generated by Django 5.2.17 on 2026-09-15 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, drop_no_delete, enable_rls, no_delete


class Migration(migrations.Migration):
    """P6 chunk 3, task 4: public_holiday_observance.

    Enables RLS in the SAME migration that creates the table — chunk 1's
    D-169 is the standing reminder of what happens when that step is
    forgotten. Also closes a gap this table's own FK opens: `public_holiday`
    was never added to `statutory/migrations/0008`'s `GUARDED` list, because
    nothing pointed a FORCE-RLS tenant table at it until now. D-76's own
    reasoning applies unchanged — a session with no tenant pinned could
    delete a `public_holiday` row and orphan this table's referencing rows,
    which this table's own RLS would then hide from the delete's own
    protection check. `NO_DELETE_FUNCTION` was created once already, in
    `statutory/migrations/0008`; this migration only attaches the trigger.
    """

    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("employers", "0004_payroll_component"),
        ("leave", "0009_leave_transaction_application_fk"),
        ("statutory", "0012_notice_band_inclusivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHolidayObservance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observance_date", models.DateField(db_index=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "is_observed",
                    models.BooleanField(
                        default=True,
                        help_text="FALSE = this employer's employees worked this day as ordinary.",
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_holiday_observances",
                        to="employers.employer",
                    ),
                ),
                (
                    "public_holiday",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for an employer-specific day not on the statutory calendar.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="statutory.publicholiday",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "public_holiday_observance",
                "ordering": ["employer_id", "observance_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employer", "observance_date"),
                        name="uniq_public_holiday_observance_per_employer_date",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            enable_rls("public_holiday_observance"), disable_rls("public_holiday_observance")
        ),
        migrations.RunSQL(no_delete("public_holiday"), drop_no_delete("public_holiday")),
    ]
