# Generated by Django 5.2.17 on 2026-09-16 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0008_employeeimportbatch_employee_created_by_import_batch_and_more'),
        ('leave', '0010_public_holiday_observance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='unpaid_hours',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Portion that will be unpaid, in hours: beyond the balance, unpaid by nature, or withheld for want of evidence. Zero on a days-basis application (D-188).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='unpaid_days',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Portion that will be unpaid, in days. Zero on an hours-basis application.', max_digits=7),
        ),
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.CheckConstraint(condition=models.Q(('unpaid_hours__gte', 0)), name='leave_application_unpaid_hours_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('total_hours__isnull', True), ('unpaid_hours', 0)), models.Q(('total_hours__isnull', False), ('unpaid_days', 0)), _connector='OR'), name='leave_application_unpaid_in_its_own_unit'),
        ),
    ]
