# Generated by Django 5.2.17 on 2026-09-18 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0011_accommodation_deduction_percentage'),
        ('leave', '0011_leave_application_unpaid_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='parental_child_under_age_limit',
            field=models.BooleanField(blank=True, help_text="Adoption only. Declared, not derived - the child's date of birth is not stored.", null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='parental_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='parental_declared_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='parental_event_date',
            field=models.DateField(blank=True, db_index=True, help_text='The birth, placement or adoption order date this leave relates to.', null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='parental_relationship_shape',
            field=models.CharField(blank=True, help_text='Declared: single parent, only employed party, or both employed.', max_length=30),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='parental_share_days',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='parental_share_months',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parental_declared_at__isnull', True), ('parental_event_date__isnull', True), ('parental_relationship_shape', ''), ('parental_share_days__isnull', True), ('parental_share_months__isnull', True)), models.Q(('parental_declared_at__isnull', False), ('parental_event_date__isnull', False), ('parental_share_days__isnull', False), ('parental_share_months__isnull', False), models.Q(('parental_relationship_shape', ''), _negated=True)), _connector='OR'), name='leave_application_parental_declaration_is_whole'),
        ),
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.CheckConstraint(condition=models.Q(('parental_relationship_shape', ''), ('parental_relationship_shape__in', ['single_parent', 'only_employed_party', 'both_employed']), _connector='OR'), name='leave_application_parental_shape_is_known'),
        ),
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.CheckConstraint(condition=models.Q(('parental_share_months__isnull', True), models.Q(('parental_share_days__gte', 0), ('parental_share_months__gte', 0)), _connector='OR'), name='leave_application_parental_share_not_negative'),
        ),
    ]
