# Generated by Django 5.2.17 on 2026-09-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_maternity_and_adoption_draw_on_parental'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='expected_date_of_confinement',
            field=models.DateField(blank=True, help_text='PRENATAL only. The expected date of birth this clinic day counts against, as certified under clause 13.1(b)(i).', null=True),
        ),
    ]
