# Generated by Django 5.2.17 on 2026-09-25 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0015_entitlement_contractual_grant'),
        ('leave', '0014_leaveapplication_expected_date_of_confinement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='beyond_statute_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='beyond_statute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='leaveapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('beyond_statute_authorised_by__isnull', True), ('beyond_statute_reason', '')), models.Q(('beyond_statute_authorised_by__isnull', False), models.Q(('beyond_statute_reason', ''), _negated=True)), _connector='OR'), name='leave_application_beyond_statute_is_named_and_reasoned'),
        ),
    ]
