# Generated by Django 5.2.17 on 2026-09-25 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employers', '0005_pay_group_public_uid'),
        ('leave', '0015_contractual_family_responsibility'),
        ('statutory', '0027_notice_band_superseded_by_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholidayobservance',
            name='substitute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchanged_holiday', to='leave.publicholidayobservance'),
        ),
        migrations.AddField(
            model_name='publicholidayobservance',
            name='treatment',
            field=models.CharField(choices=[('observed', 'Observed'), ('exchanged', 'Exchanged for another day (PHA s2(2))'), ('worked_by_agreement', 'Worked by agreement (BCEA s18(1))'), ('substitute', 'Substitute for an exchanged holiday')], default='observed', max_length=30),
        ),
        migrations.AlterField(
            model_name='publicholidayobservance',
            name='is_observed',
            field=models.BooleanField(default=True, help_text="Sheet 02's column. Derived: FALSE exactly when the day was exchanged."),
        ),
        migrations.AddConstraint(
            model_name='publicholidayobservance',
            constraint=models.CheckConstraint(condition=models.Q(('treatment__in', ['observed', 'exchanged', 'worked_by_agreement', 'substitute'])), name='observance_treatment_is_known'),
        ),
        migrations.AddConstraint(
            model_name='publicholidayobservance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_observed', False), ('treatment', 'exchanged')), models.Q(models.Q(('treatment', 'exchanged'), _negated=True), ('is_observed', True)), _connector='OR'), name='observance_is_observed_follows_treatment'),
        ),
        migrations.AddConstraint(
            model_name='publicholidayobservance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('treatment__in', ['exchanged', 'worked_by_agreement']), _negated=True), ('public_holiday__isnull', False), _connector='OR'), name='observance_exchange_or_work_names_the_holiday'),
        ),
        migrations.AddConstraint(
            model_name='publicholidayobservance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('treatment', 'substitute'), _negated=True), ('public_holiday__isnull', True), _connector='OR'), name='observance_substitute_is_off_the_calendar'),
        ),
        migrations.AddConstraint(
            model_name='publicholidayobservance',
            constraint=models.CheckConstraint(condition=models.Q(('substitute__isnull', True), ('treatment', 'exchanged'), _connector='OR'), name='observance_only_an_exchange_has_a_substitute'),
        ),
    ]
