# Generated by Django 5.2.17 on 2026-09-13 11:01

import core.db.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """The employer, its statutory registrations and its bank accounts.

    Every table here is tenant-scoped, so every one gets ``enable_rls`` below. That
    is not optional and not a nicety: the generated isolation suite discovers each
    new ``TenantScopedModel`` from the registry and fails if row-level security is
    not enabled AND forced on its table. A model added without these three lines
    fails CI on the commit that adds it, which is the whole point of generating the
    suite rather than writing it.

    ``employer_bank_account.account_number`` is the first encrypted column in the
    schema. It is a TEXT column holding a Fernet token, not a CHAR of the account
    number's length - see ``core/db/fields.py`` for why it cannot be searched and
    what the two companion columns are for.
    """


    initial = True

    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("statutory", "0007_bank_account_length_may_be_unknown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("trading_name", models.CharField(db_index=True, max_length=150)),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text="As registered. Blank for a household, which has no registered name.",
                        max_length=200,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual or household"),
                            ("sole_proprietor", "Sole proprietor"),
                            ("company", "Company"),
                            ("close_corporation", "Close corporation"),
                            ("trust", "Trust"),
                            ("partnership", "Partnership"),
                            ("non_profit", "Non-profit organisation"),
                        ],
                        default="individual",
                        max_length=30,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="CIPC registration number, where there is one.",
                        max_length=50,
                    ),
                ),
                ("income_tax_reference", models.CharField(blank=True, max_length=20)),
                ("physical_line1", models.CharField(blank=True, max_length=120)),
                ("physical_line2", models.CharField(blank=True, max_length=120)),
                ("physical_suburb", models.CharField(blank=True, max_length=120)),
                ("physical_city", models.CharField(blank=True, max_length=120)),
                (
                    "physical_municipality",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="What municipality_area_map resolves against.",
                        max_length=120,
                    ),
                ),
                (
                    "physical_province_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EC", "Eastern Cape"),
                            ("FS", "Free State"),
                            ("GP", "Gauteng"),
                            ("KZN", "KwaZulu-Natal"),
                            ("LP", "Limpopo"),
                            ("MP", "Mpumalanga"),
                            ("NC", "Northern Cape"),
                            ("NW", "North West"),
                            ("WC", "Western Cape"),
                        ],
                        max_length=10,
                    ),
                ),
                ("physical_postal_code", models.CharField(blank=True, max_length=10)),
                ("contact_name", models.CharField(blank=True, max_length=150)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("onboarded_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete. Statutory retention outlasts the customer relationship.",
                        null=True,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        help_text="Decides every rule set and minimum wage this employer is measured against.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employers",
                        to="statutory.sector",
                    ),
                ),
                (
                    "sector_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contract cleaning only, and normally derived from the workplace address rather than asked. NULL for a sector that does not use area rates.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employers",
                        to="statutory.sectorarea",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employer",
                "ordering": ["trading_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployerBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch_code", models.CharField(max_length=10)),
                ("account_holder", models.CharField(max_length=150)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("cheque", "Cheque or current"),
                            ("savings", "Savings"),
                            ("transmission", "Transmission"),
                        ],
                        default="cheque",
                        max_length=20,
                    ),
                ),
                (
                    "account_number",
                    core.db.fields.EncryptedCharField(max_plaintext_length=30),
                ),
                (
                    "account_number_last4",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                (
                    "account_number_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Keyed HMAC of the normalised number. The only way to ask 'same account?'.",
                        max_length=64,
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                ("effective_from", models.DateField()),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means currently in use.",
                        null=True,
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employer_accounts",
                        to="statutory.bank",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_accounts",
                        to="employers.employer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employer_bank_account",
                "ordering": ["employer_id", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="EmployerStatutoryRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("paye", "PAYE (SARS)"),
                            ("sdl", "SDL (SARS)"),
                            ("uif_sars", "UIF via SARS"),
                            ("uif_del", "UIF via Department of Employment and Labour"),
                            ("coida", "COIDA (Compensation Fund)"),
                            ("bargaining_council", "Bargaining council"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=40)),
                ("registered_from", models.DateField()),
                (
                    "registered_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means currently registered.",
                        null=True,
                    ),
                ),
                (
                    "is_exempt",
                    models.BooleanField(
                        default=False,
                        help_text="SDL: the employer reasonably believes the next twelve months' leviable amount will not exceed the threshold. Forward-looking and human-set.",
                    ),
                ),
                ("exemption_reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statutory_registrations",
                        to="employers.employer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employer_statutory_registration",
                "ordering": ["employer_id", "registration_type", "-registered_from"],
            },
        ),
        migrations.AddIndex(
            model_name="employer",
            index=models.Index(
                fields=["tenant", "is_active"], name="employer_tenant__630673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employer",
            index=models.Index(fields=["sector"], name="employer_sector__7802f2_idx"),
        ),
        migrations.AddConstraint(
            model_name="employer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "trading_name"), name="uniq_employer_name_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="employer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("deactivated_at__isnull", True), ("is_active", True)),
                    models.Q(("deactivated_at__isnull", False), ("is_active", False)),
                    _connector="OR",
                ),
                name="employer_deactivated_at_matches_is_active",
            ),
        ),
        migrations.AddIndex(
            model_name="employerbankaccount",
            index=models.Index(
                fields=["tenant", "employer"], name="employer_ba_tenant__92d5d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employerbankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="employer_bank_account_period_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="employerbankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True), ("is_primary", True)
                ),
                fields=("employer",),
                name="uniq_live_primary_account_per_employer",
            ),
        ),
        migrations.AddIndex(
            model_name="employerstatutoryregistration",
            index=models.Index(
                fields=["tenant", "employer", "registration_type"],
                name="employer_st_tenant__e6f06e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="employerstatutoryregistration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("registered_to__isnull", True),
                    ("registered_to__gt", models.F("registered_from")),
                    _connector="OR",
                ),
                name="employer_registration_period_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="employerstatutoryregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("registered_to__isnull", True)),
                fields=("employer", "registration_type"),
                name="uniq_live_registration_per_employer_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="employerstatutoryregistration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_exempt", False),
                    models.Q(("exemption_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="employer_registration_exemption_has_a_reason",
            ),
        ),
            migrations.RunSQL(enable_rls("employer"), disable_rls("employer")),
        migrations.RunSQL(
            enable_rls("employer_statutory_registration"),
            disable_rls("employer_statutory_registration"),
        ),
        migrations.RunSQL(
            enable_rls("employer_bank_account"), disable_rls("employer_bank_account")
        ),
    ]
