# Generated by Django 5.2.17 on 2026-09-13 11:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """Employer settings and workplaces, both tenant-scoped.

    ``enable_rls`` on both, for the reason spelled out in 0001: the generated
    isolation suite discovers every ``TenantScopedModel`` from the registry and fails
    if row-level security is not enabled AND forced. A model added without it fails
    CI on the commit that adds it.
    """


    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("employers", "0001_initial"),
        ("statutory", "0008_reference_tables_refuse_deletes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("setting_key", models.CharField(db_index=True, max_length=60)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("numeric", "Numeric"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value_text", models.CharField(blank=True, max_length=200)),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "set_by_employer",
                    models.BooleanField(
                        default=False,
                        help_text="False means this is still the value seeded at onboarding. True means a person chose it. The difference matters when a sector default changes.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings",
                        to="employers.employer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employer_setting",
                "ordering": ["employer_id", "setting_key"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "employer"],
                        name="employer_se_tenant__0032f9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employer", "setting_key"),
                        name="uniq_setting_per_employer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("value_boolean__isnull", True),
                                ("value_date__isnull", True),
                                ("value_numeric__isnull", True),
                                ("value_type", "text"),
                            ),
                            models.Q(
                                ("value_boolean__isnull", True),
                                ("value_date__isnull", True),
                                ("value_numeric__isnull", False),
                                ("value_text", ""),
                                ("value_type", "numeric"),
                            ),
                            models.Q(
                                ("value_boolean__isnull", False),
                                ("value_date__isnull", True),
                                ("value_numeric__isnull", True),
                                ("value_text", ""),
                                ("value_type", "boolean"),
                            ),
                            models.Q(
                                ("value_boolean__isnull", True),
                                ("value_date__isnull", False),
                                ("value_numeric__isnull", True),
                                ("value_text", ""),
                                ("value_type", "date"),
                            ),
                            _connector="OR",
                        ),
                        name="employer_setting_exactly_one_typed_value",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text="Contract cleaning: whose premises these are. Blank for a household.",
                        max_length=150,
                    ),
                ),
                (
                    "contract_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="What cost-per-contract reporting groups on.",
                        max_length=60,
                    ),
                ),
                ("line1", models.CharField(blank=True, max_length=120)),
                ("line2", models.CharField(blank=True, max_length=120)),
                ("suburb", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "municipality",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="What municipality_area_map resolves the wage area from.",
                        max_length=120,
                    ),
                ),
                (
                    "province_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EC", "Eastern Cape"),
                            ("FS", "Free State"),
                            ("GP", "Gauteng"),
                            ("KZN", "KwaZulu-Natal"),
                            ("LP", "Limpopo"),
                            ("MP", "Mpumalanga"),
                            ("NC", "Northern Cape"),
                            ("NW", "North West"),
                            ("WC", "Western Cape"),
                        ],
                        max_length=10,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                (
                    "area_resolved_on",
                    models.DateField(
                        blank=True,
                        help_text="The date the mapping was read. The mapping itself is effective-dated.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workplaces",
                        to="employers.employer",
                    ),
                ),
                (
                    "sector_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved from the municipality and STORED, so a re-run reproduces the area that applied at the time. NULL means unresolved, which blocks payroll for a sector that uses area rates rather than guessing.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workplaces",
                        to="statutory.sectorarea",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workplace",
                "ordering": ["employer_id", "name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "employer"],
                        name="workplace_tenant__4fbe7b_idx",
                    ),
                    models.Index(
                        fields=["contract_reference"],
                        name="workplace_contrac_aa3e3a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employer", "name"),
                        name="uniq_workplace_name_per_employer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("area_resolved_on__isnull", True),
                                ("sector_area__isnull", True),
                            ),
                            models.Q(
                                ("area_resolved_on__isnull", False),
                                ("sector_area__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="workplace_area_and_resolution_date_together",
                    ),
                ],
            },
        ),
            migrations.RunSQL(enable_rls("employer_setting"), disable_rls("employer_setting")),
        migrations.RunSQL(enable_rls("workplace"), disable_rls("workplace")),
    ]
