# Generated by Django 5.2.17 on 2026-09-13 11:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """The pay group: a pay basis plus the calendar its periods fall on.

    Tenant-scoped, so ``enable_rls`` below - the generated isolation suite fails
    without it.

    Every column is the workbook's, including the three period end rules and the
    1-28 cap on the fixed day of month. The cap is why February needs no special
    case: a period that always ends on the 28th or earlier behaves the same in every
    month of the year.
    """


    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("employers", "0002_employersetting_workplace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Monthly staff', 'Weekly cleaners'.",
                        max_length=100,
                    ),
                ),
                (
                    "pay_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "period_end_rule",
                    models.CharField(
                        choices=[
                            ("calendar_month_end", "Last day of the calendar month"),
                            ("fixed_day_of_month", "A fixed day of the month"),
                            ("week_ending_day", "A fixed weekday"),
                        ],
                        default="calendar_month_end",
                        max_length=30,
                    ),
                ),
                (
                    "week_ending_weekday",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="0=Monday .. 6=Sunday. Weekly and fortnightly.",
                        null=True,
                    ),
                ),
                (
                    "period_end_day_of_month",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="1-28 for fixed_day_of_month. Capped at 28 so February behaves like every other month instead of needing its own clamping rule.",
                        null=True,
                    ),
                ),
                (
                    "payment_day_offset",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Days after period end that payment is made.",
                    ),
                ),
                (
                    "first_period_start",
                    models.DateField(help_text="Anchors period generation."),
                ),
                (
                    "default_days_per_week",
                    models.DecimalField(decimal_places=2, default=5, max_digits=4),
                ),
                (
                    "default_hours_per_day",
                    models.DecimalField(decimal_places=2, default=9, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_groups",
                        to="employers.employer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_group",
                "ordering": ["employer_id", "name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "pay_frequency"],
                        name="pay_group_tenant__6e7c6e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employer", "name"), name="uniq_pay_group_per_employer"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_end_day_of_month__isnull", True),
                            models.Q(
                                ("period_end_day_of_month__gte", 1),
                                ("period_end_day_of_month__lte", 28),
                            ),
                            _connector="OR",
                        ),
                        name="pay_group_period_end_day_is_1_to_28",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("week_ending_weekday__isnull", True),
                            models.Q(
                                ("week_ending_weekday__gte", 0),
                                ("week_ending_weekday__lte", 6),
                            ),
                            _connector="OR",
                        ),
                        name="pay_group_week_ending_weekday_is_a_weekday",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("period_end_rule", "week_ending_day"), _negated=True
                            ),
                            ("week_ending_weekday__isnull", False),
                            _connector="OR",
                        ),
                        name="pay_group_week_ending_rule_needs_a_weekday",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("period_end_rule", "fixed_day_of_month"), _negated=True
                            ),
                            ("period_end_day_of_month__isnull", False),
                            _connector="OR",
                        ),
                        name="pay_group_fixed_day_rule_needs_a_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_days_per_week__gt", 0),
                            ("default_days_per_week__lte", 7),
                        ),
                        name="pay_group_days_per_week_is_a_week",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_hours_per_day__gt", 0),
                            ("default_hours_per_day__lte", 24),
                        ),
                        name="pay_group_hours_per_day_is_a_day",
                    ),
                ],
            },
        ),
            migrations.RunSQL(enable_rls("pay_group"), disable_rls("pay_group")),
    ]
