# Generated by Django 5.2.17 on 2026-09-13 12:15

import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import (
    DROP_SYSTEM_ROW_LOCK_FUNCTION,
    SYSTEM_ROW_LOCK_FUNCTION,
    disable_rls,
    drop_lock_system_rows,
    enable_rls_shared,
    lock_system_rows,
)


class Migration(migrations.Migration):
    """The payroll component catalogue, and the first shared-tenancy table.

    Three operations after the table, and each closes a different gap:

    ``enable_rls_shared``
        The third tenancy policy. A NULL ``tenant_id`` here means *available to
        all* rather than *belongs to the platform and no tenant may see it*, which
        is what the same NULL means under ``enable_rls_optional``. Read and write
        differ: a tenant reads the catalogue and its own rows, and writes only its
        own.

    ``SYSTEM_ROW_LOCK_FUNCTION`` + ``lock_system_rows``
        A DELETE is checked against a policy's USING clause only - there is no
        WITH CHECK for DELETE, because there is no new row to check. So a tenant
        that can *see* a shared row can *delete* it, and the catalogue every other
        employer's payslips point at loses a line. A trigger is the only layer
        that runs regardless of what the deleting session can see, and it binds
        the table owner, which the application connects as.

    Without the first of these the generated isolation suite fails, which is the
    intended safety net.
    """

    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("employers", "0003_paygroup"),
        ("statutory", "0008_reference_tables_refuse_deletes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="BASIC, OT_1_5, UIF_EE, PAYE …", max_length=40
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("deduction", "Deduction"),
                            ("employer_contribution", "Employer contribution"),
                            ("informational", "Informational"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed amount"),
                            ("rate_x_units", "Rate × units"),
                            ("percentage_of_base", "Percentage of a base"),
                            ("formula", "Formula"),
                            (
                                "statutory",
                                "Statutory — the figure comes from reference data",
                            ),
                        ],
                        default="fixed",
                        max_length=30,
                    ),
                ),
                (
                    "default_rate_multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Employer-defined components only. A statutory multiplier belongs in working_time_rule_set with its gazette citation, never here.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "percentage_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Employer-defined components only. Same reason as the multiplier.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_uif_base", models.BooleanField(default=True)),
                ("is_sdl_base", models.BooleanField(default=True)),
                ("is_coida_base", models.BooleanField(default=True)),
                (
                    "affects_leave_pay_average",
                    models.BooleanField(
                        default=False,
                        help_text="Part of remuneration when leave, notice and severance are calculated. BCEA s35(5) determination, GN 691 in Government Gazette 24889.",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System components cannot be edited or deleted.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.SmallIntegerField(default=0, help_text="Payslip ordering."),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sars_source_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="Decides the IRP5 line. The four base flags below must match it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_components",
                        to="statutory.sarssourcecode",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_component",
                "ordering": ["display_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["component_type", "is_active"],
                        name="payroll_com_compone_8d5bee_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.comparison.Coalesce(
                            "tenant_id", models.Value(0)
                        ),
                        models.F("code"),
                        name="uniq_component_code_per_tenant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "component_type__in",
                                [
                                    "earning",
                                    "deduction",
                                    "employer_contribution",
                                    "informational",
                                ],
                            )
                        ),
                        name="payroll_component_type_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "calculation_method__in",
                                [
                                    "fixed",
                                    "rate_x_units",
                                    "percentage_of_base",
                                    "formula",
                                    "statutory",
                                ],
                            )
                        ),
                        name="payroll_component_calculation_method_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tenant__isnull", False),
                            ("is_system", True),
                            _connector="OR",
                        ),
                        name="payroll_component_shared_rows_are_system_rows",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tenant__isnull", True),
                            ("is_system", False),
                            _connector="OR",
                        ),
                        name="payroll_component_system_rows_are_shared_rows",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("percentage_value__isnull", True),
                            ("percentage_value__gte", 0),
                            _connector="OR",
                        ),
                        name="payroll_component_percentage_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_rate_multiplier__isnull", True),
                            ("default_rate_multiplier__gte", 0),
                            _connector="OR",
                        ),
                        name="payroll_component_multiplier_not_negative",
                    ),
                ],
            },
        ),
        migrations.RunSQL(SYSTEM_ROW_LOCK_FUNCTION, DROP_SYSTEM_ROW_LOCK_FUNCTION),
        migrations.RunSQL(
            enable_rls_shared("payroll_component"), disable_rls("payroll_component")
        ),
        migrations.RunSQL(
            lock_system_rows("payroll_component"),
            drop_lock_system_rows("payroll_component"),
        ),
    ]
