# Generated by Django 5.2.17 on 2026-09-13 13:20

import core.db.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """The employee and its two identity children. Domain 5, phase P4.

    All three are tenant-scoped, so all three call ``enable_rls`` below — the
    generated isolation suite fails without it, which is the intended safety net.

    **The ICU collation on the two sort columns is set HERE and nowhere else.**
    Changing a collation after the fact rewrites the table and every index on it
    (D-17), and this table is the one that grows to hundreds of thousands of rows
    in a contract cleaning tenant. ``en-ZA-x-icu`` is deterministic, and the
    expression lower-cases rather than the collation doing it, so ``LIKE`` and
    index-backed prefix search keep working.

    ``employee_born_before_today`` holds a STABLE function rather than an immutable
    one, which PostgreSQL accepts. It is safe in this direction only: ``< today``
    can only become more permissive as time passes, so a row valid when written
    stays valid through a dump, a restore and a table rewrite.
    """

    initial = True

    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("employers", "0004_payroll_component"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "employee_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique within the employer. Generated when blank, and editable after.",
                        max_length=30,
                    ),
                ),
                ("first_name", models.CharField(db_index=True, max_length=80)),
                ("middle_names", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(db_index=True, max_length=80)),
                ("preferred_name", models.CharField(blank=True, max_length=80)),
                (
                    "initials",
                    models.CharField(
                        blank=True, help_text="Required on the IRP5.", max_length=10
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Drives age-based rebates and the BCEA s43 minimum-age block."
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("not_specified", "Not specified"),
                        ],
                        help_text="Collected for the EEA return and the UI-19 only.",
                        max_length=20,
                    ),
                ),
                ("nationality_code", models.CharField(default="ZA", max_length=2)),
                (
                    "home_language",
                    models.CharField(
                        blank=True,
                        help_text="Selects the contract language.",
                        max_length=40,
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("sa_id", "South African ID"),
                            ("passport", "Passport"),
                            ("asylum_permit", "Asylum seeker permit"),
                            ("work_permit", "Work permit"),
                        ],
                        default="sa_id",
                        max_length=20,
                    ),
                ),
                (
                    "id_number",
                    core.db.fields.EncryptedCharField(
                        help_text="Encrypted at rest. POPIA special personal information; never queryable.",
                        max_plaintext_length=30,
                    ),
                ),
                (
                    "id_number_last4",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                (
                    "id_number_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Keyed HMAC, scoped to the tenant. The duplicate-employee guard.",
                        max_length=64,
                    ),
                ),
                (
                    "id_number_verified",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="The checksum and the date of birth agree. Only ever true for an SA ID.",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        db_index=True,
                        help_text="Mandatory. Carries the OTP and the payslip notice where email fails.",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Mandatory unless has_no_email is set. Stored lower-cased.",
                        max_length=254,
                    ),
                ),
                (
                    "has_no_email",
                    models.BooleanField(
                        default=False,
                        help_text="An honest flag for a worker with no address. Routes delivery to SMS and stops employers inventing addresses to satisfy a mandatory field (D-10).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("on_leave", "On leave"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True,
                        help_text="Counts toward the subscription headcount.",
                    ),
                ),
                (
                    "first_engagement_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "latest_termination_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "current_pay_basis",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="CACHE (D-18).",
                        max_length=20,
                    ),
                ),
                (
                    "sort_name_first",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Concat(
                                "first_name", models.Value(" "), "last_name"
                            )
                        ),
                        output_field=models.CharField(
                            db_collation="en-ZA-x-icu", max_length=161
                        ),
                    ),
                ),
                (
                    "sort_name_last",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Lower(
                            django.db.models.functions.text.Concat(
                                "last_name", models.Value(" "), "first_name"
                            )
                        ),
                        output_field=models.CharField(
                            db_collation="en-ZA-x-icu", max_length=161
                        ),
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_pay_group",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="CACHE (D-18). NULL means not yet computed, not 'no pay group'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="employers.paygroup",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="employers.employer",
                    ),
                ),
                (
                    "photo_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.fileobject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee",
                "ordering": ["sort_name_last"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_type",
                    models.CharField(
                        choices=[("residential", "Residential"), ("postal", "Postal")],
                        default="residential",
                        max_length=20,
                    ),
                ),
                ("line1", models.CharField(max_length=150)),
                ("line2", models.CharField(blank=True, max_length=150)),
                ("suburb", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "province_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EC", "Eastern Cape"),
                            ("FS", "Free State"),
                            ("GP", "Gauteng"),
                            ("KZN", "KwaZulu-Natal"),
                            ("LP", "Limpopo"),
                            ("MP", "Mpumalanga"),
                            ("NC", "Northern Cape"),
                            ("NW", "North West"),
                            ("WC", "Western Cape"),
                        ],
                        max_length=10,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("country_code", models.CharField(default="ZA", max_length=2)),
                ("effective_from", models.DateField()),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means current.",
                        null=True,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_address",
                "ordering": ["employee_id", "address_type", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency contact"),
                            ("next_of_kin", "Next of kin"),
                            ("beneficiary", "Beneficiary"),
                        ],
                        default="emergency",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("relationship", models.CharField(blank=True, max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_contact",
                "ordering": ["employee_id", "contact_type", "-is_primary"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["tenant", "status"], name="employee_tenant__ccac82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["tenant", "sort_name_first"], name="employee_tenant__9f0515_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["tenant", "sort_name_last"], name="employee_tenant__216323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["tenant", "current_pay_group"],
                name="employee_tenant__f6b06e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("employer", "employee_number"),
                name="uniq_employee_number_per_employer",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id_number_hash"),
                name="uniq_employee_id_number_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "id_type__in",
                        ["sa_id", "passport", "asylum_permit", "work_permit"],
                    )
                ),
                name="employee_id_type_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_of_birth__lt", django.db.models.functions.datetime.Now())
                ),
                name="employee_born_before_today",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("has_no_email", True),
                    models.Q(("email", ""), _negated=True),
                    _connector="OR",
                ),
                name="employee_has_an_email_or_says_it_has_none",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeaddress",
            index=models.Index(
                fields=["employee", "address_type", "-effective_from"],
                name="employee_ad_employe_e9318e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeaddress",
            index=models.Index(
                fields=["tenant"], name="employee_ad_tenant__b898ea_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeaddress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="employee_address_period_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="employeecontact",
            index=models.Index(
                fields=["employee", "contact_type"],
                name="employee_co_employe_6f94b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeecontact",
            index=models.Index(
                fields=["tenant"], name="employee_co_tenant__856cc9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeecontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("employee", "contact_type"),
                name="uniq_primary_contact_per_type",
            ),
        ),
        migrations.RunSQL(enable_rls("employee"), disable_rls("employee")),
        migrations.RunSQL(enable_rls("employee_address"), disable_rls("employee_address")),
        migrations.RunSQL(enable_rls("employee_contact"), disable_rls("employee_contact")),
    ]
