# Generated by Django 5.2.17 on 2026-09-13 14:26

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import statutory.models
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """Engagements and positions. Both tenant-scoped, so both call ``enable_rls``.

    The exclusion constraint on ``employee_position`` is the one worth noticing. The
    unique on ``(employee, effective_from)`` only stops two positions STARTING on the
    same day; a back-dated promotion starts inside the previous position's period and
    slips straight past it. Two positions in force at once means two job grades, so
    two minimum wages, and the ORM picks one by ordering — which is a wrong payslip
    that nothing reports.
    """

    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("employees", "0001_initial"),
        ("employers", "0004_payroll_component"),
        ("statutory", "0009_parameter_unit_years"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement_number",
                    models.SmallIntegerField(
                        default=1,
                        help_text="1 for the first engagement, 2 for a re-hire, and so on.",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, help_text="Date of engagement."),
                ),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("fixed_term", "Fixed term"),
                            ("temporary", "Temporary"),
                            ("casual", "Casual"),
                            ("project", "Project"),
                        ],
                        default="permanent",
                        max_length=30,
                    ),
                ),
                (
                    "fixed_term_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Required for a fixed-term contract.",
                        null=True,
                    ),
                ),
                (
                    "fixed_term_reason",
                    models.CharField(
                        blank=True,
                        help_text="LRA s198B justification for employing on a fixed term.",
                        max_length=255,
                    ),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Last day of service.",
                        null=True,
                    ),
                ),
                (
                    "termination_reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resignation", "Resignation"),
                            ("dismissal_misconduct", "Dismissal — misconduct"),
                            ("dismissal_incapacity", "Dismissal — incapacity"),
                            ("retrenchment", "Retrenchment (operational requirements)"),
                            ("end_of_contract", "End of fixed-term contract"),
                            ("retirement", "Retirement"),
                            ("death", "Death"),
                            ("absconded", "Absconded"),
                            ("mutual_separation", "Mutual separation"),
                        ],
                        max_length=40,
                    ),
                ),
                ("termination_notes", models.TextField(blank=True)),
                ("notice_given_date", models.DateField(blank=True, null=True)),
                (
                    "notice_worked",
                    models.BooleanField(
                        blank=True,
                        help_text="FALSE triggers notice pay in the termination engine.",
                        null=True,
                    ),
                ),
                (
                    "uif_status_code",
                    models.CharField(
                        blank=True,
                        help_text="UI-19 reason code for the declaration.",
                        max_length=10,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="At most one per employee. Not the same as 'not terminated'.",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_engagement",
                "ordering": ["employee_id", "-engagement_number"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_title",
                    models.CharField(
                        help_text="Free text, as the employer says it.", max_length=120
                    ),
                ),
                (
                    "site_assignment",
                    models.CharField(
                        choices=[
                            ("single_site", "One site"),
                            ("multi_site", "More than one site"),
                        ],
                        default="single_site",
                        max_length=20,
                    ),
                ),
                (
                    "occupational_level",
                    models.CharField(
                        blank=True,
                        help_text="For EEA reporting if it is ever required.",
                        max_length=40,
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means current.",
                        null=True,
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new_engagement", "New engagement"),
                            ("promotion", "Promotion"),
                            ("transfer", "Transfer"),
                            ("redeployment", "Redeployment"),
                            ("correction", "Correction"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="employees.employee",
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="employees.employeeengagement",
                    ),
                ),
                (
                    "job_grade",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selects the applicable minimum wage row.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="statutory.jobgrade",
                    ),
                ),
                (
                    "reports_to_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="employers.workplace",
                    ),
                ),
            ],
            options={
                "db_table": "employee_position",
                "ordering": ["employee_id", "-effective_from"],
            },
        ),
        migrations.AddIndex(
            model_name="employeeengagement",
            index=models.Index(
                fields=["tenant", "start_date"], name="employee_en_tenant__521b0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeengagement",
            index=models.Index(
                fields=["termination_date"], name="employee_en_termina_92b628_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeengagement",
            constraint=models.UniqueConstraint(
                fields=("employee", "engagement_number"),
                name="uniq_engagement_number_per_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeengagement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("employee",),
                name="uniq_current_engagement_per_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeengagement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("termination_date__isnull", True),
                    ("termination_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="engagement_ends_on_or_after_it_starts",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeengagement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("contract_type", "fixed_term"), _negated=True),
                    ("fixed_term_end_date__isnull", False),
                    _connector="OR",
                ),
                name="engagement_fixed_term_has_an_end_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeengagement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_current", False),
                    ("termination_date__isnull", True),
                    _connector="OR",
                ),
                name="engagement_current_means_not_yet_terminated",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeengagement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("termination_date__isnull", True),
                    models.Q(("termination_reason_code", ""), _negated=True),
                    _connector="OR",
                ),
                name="engagement_termination_has_a_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeengagement",
            constraint=models.CheckConstraint(
                condition=models.Q(("engagement_number__gte", 1)),
                name="engagement_number_starts_at_one",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeposition",
            index=models.Index(
                fields=["employee", "-effective_from"],
                name="employee_po_employe_e7d6a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeposition",
            index=models.Index(
                fields=["tenant"], name="employee_po_tenant__00f1ff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeposition",
            constraint=models.UniqueConstraint(
                fields=("employee", "effective_from"),
                name="uniq_position_start_per_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="employee_position_period_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeposition",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        statutory.models.DateRange(
                            "effective_from",
                            "effective_to",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("employee", "="),
                ],
                name="employee_position_no_overlapping_periods",
            ),
        ),
        migrations.RunSQL(
            enable_rls("employee_engagement"), disable_rls("employee_engagement")
        ),
        migrations.RunSQL(enable_rls("employee_position"), disable_rls("employee_position")),
    ]
