# Generated by Django 5.2.17 on 2026-09-13 14:42

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import statutory.models
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """The pay rate. Tenant-scoped, so ``enable_rls`` below.

    The exclusion constraint matters more here than anywhere else in this app. Two
    rates in force at once means two answers to "what is this employee paid", with
    the ORM choosing by row order — and the unique on (employee, effective_from)
    only stops two rows STARTING on one day. A back-dated increase starts inside the
    open period and slips straight past it.
    """

    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("employees", "0002_engagement_and_position"),
        ("employers", "0004_payroll_component"),
        ("statutory", "0009_parameter_unit_years"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeRemuneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_basis",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "rate_amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="As captured, in the unit of pay_basis.",
                        max_digits=14,
                    ),
                ),
                (
                    "derived_hourly_rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Normalised. The single input every calculator uses.",
                        max_digits=14,
                    ),
                ),
                (
                    "derived_daily_rate",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "derived_monthly_rate",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                (
                    "hours_per_day",
                    models.DecimalField(decimal_places=2, default=9, max_digits=5),
                ),
                (
                    "days_per_week",
                    models.DecimalField(decimal_places=2, default=5, max_digits=4),
                ),
                (
                    "hours_per_week",
                    models.DecimalField(decimal_places=2, default=45, max_digits=5),
                ),
                (
                    "is_below_minimum",
                    models.BooleanField(
                        default=False,
                        help_text="A flag, not a block. Allows the correction workflow.",
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means current.",
                        null=True,
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new_engagement", "New engagement"),
                            ("annual_increase", "Annual increase"),
                            ("minimum_wage_uplift", "Minimum wage uplift"),
                            ("promotion", "Promotion"),
                            ("correction", "Correction"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "below_minimum_ack_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who accepted a below-minimum rate. 'The system let me' is not a defence.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remuneration",
                        to="employees.employee",
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remuneration",
                        to="employees.employeeengagement",
                    ),
                ),
                (
                    "minimum_wage_rate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The floor this rate was measured against, as at capture.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validated_remuneration",
                        to="statutory.minimumwagerate",
                    ),
                ),
                (
                    "pay_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remuneration",
                        to="employers.paygroup",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_remuneration",
                "ordering": ["employee_id", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-effective_from"],
                        name="employee_re_employe_060d8f_idx",
                    ),
                    models.Index(
                        fields=["tenant", "pay_basis"],
                        name="employee_re_tenant__1e1870_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "effective_from"),
                        name="uniq_remuneration_start_per_employee",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate_amount__gt", 0)),
                        name="remuneration_rate_is_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "pay_basis__in",
                                ["hourly", "daily", "weekly", "fortnightly", "monthly"],
                            )
                        ),
                        name="remuneration_pay_basis_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="remuneration_period_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("days_per_week__gt", 0),
                            ("hours_per_day__gt", 0),
                            ("hours_per_week__gt", 0),
                        ),
                        name="remuneration_working_pattern_is_positive",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                statutory.models.DateRange(
                                    "effective_from",
                                    "effective_to",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                            ("employee", "="),
                        ],
                        name="employee_remuneration_no_overlapping_periods",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            enable_rls("employee_remuneration"), disable_rls("employee_remuneration")
        ),
    ]
