# Generated by Django 5.2.17 on 2026-09-13 15:06

import core.db.fields
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import statutory.models
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """Work schedules, tax profiles and employee banking. Four tenant-scoped tables.

    Three of the four carry an exclusion constraint over their date range, for the
    same reason ``employee_remuneration`` does: a unique on the start date stops two
    rows beginning on one day and does nothing about a back-dated row that starts
    inside an open period. Two schedules in force means a day is both an ordinary
    working day and not one, which decides public holiday pay, the Sunday multiplier
    and how much leave a day consumes.

    ``employee_bank_account`` uses the same exclusion over its active window, so an
    employee has at most one live account on any payment date. Two would mean the
    bank file picks one by row order.
    """

    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("employees", "0003_remuneration"),
        ("statutory", "0009_parameter_unit_years"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("schedule_name", models.CharField(default="Standard", max_length=80)),
                (
                    "days_per_week",
                    models.DecimalField(decimal_places=2, default=5, max_digits=4),
                ),
                (
                    "ordinary_hours_per_week",
                    models.DecimalField(decimal_places=2, default=45, max_digits=5),
                ),
                (
                    "works_over_27_hours_week",
                    models.BooleanField(
                        default=True,
                        help_text="The SD7 rate band, declared rather than computed. The gazette owns the threshold; this says which side of it the employee is on.",
                    ),
                ),
                (
                    "cycle_length_days",
                    models.SmallIntegerField(
                        default=7,
                        help_text="7 for a weekly pattern, 14 for a rotating fortnight.",
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means current.",
                        null=True,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "work_schedule",
                "ordering": ["employee_id", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="WorkScheduleDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle_day",
                    models.SmallIntegerField(
                        help_text="0 to cycle_length_days - 1. For a 7-day cycle, 0 is Monday."
                    ),
                ),
                ("is_working_day", models.BooleanField(default=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("unpaid_break_minutes", models.SmallIntegerField(default=60)),
                (
                    "ordinary_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Net of the unpaid break.",
                        max_digits=5,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="employees.workschedule",
                    ),
                ),
            ],
            options={
                "db_table": "work_schedule_day",
                "ordering": ["work_schedule_id", "cycle_day"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("eft", "Electronic transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        default="eft",
                        max_length=20,
                    ),
                ),
                ("branch_code", models.CharField(blank=True, max_length=10)),
                (
                    "account_number",
                    core.db.fields.EncryptedCharField(
                        blank=True, default="", max_plaintext_length=30
                    ),
                ),
                (
                    "account_number_last4",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                (
                    "account_number_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Keyed HMAC, scoped to the tenant. Finds several employees on one account.",
                        max_length=64,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("current", "Current or cheque"),
                            ("savings", "Savings"),
                            ("transmission", "Transmission"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_holder_name", models.CharField(blank=True, max_length=150)),
                (
                    "account_holder_relationship",
                    models.CharField(
                        choices=[
                            ("self", "The employee"),
                            ("spouse", "Spouse"),
                            ("other", "Someone else"),
                        ],
                        default="self",
                        max_length=30,
                    ),
                ),
                ("active_from", models.DateField(db_index=True)),
                (
                    "active_to",
                    models.DateField(
                        blank=True, help_text="Exclusive. NULL means live.", null=True
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Branch code and account length checks passed.",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL when the employee is paid in cash.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_accounts",
                        to="statutory.bank",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "third_party_consent_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Written consent, required when the account is not the employee's own.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.fileobject",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_bank_account",
                "ordering": ["employee_id", "-active_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-active_from"],
                        name="employee_ba_employe_69ff05_idx",
                    ),
                    models.Index(
                        fields=["tenant", "account_number_hash"],
                        name="employee_ba_tenant__f35288_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("active_to__isnull", True),
                            ("active_to__gt", models.F("active_from")),
                            _connector="OR",
                        ),
                        name="employee_bank_account_period_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("payment_method", "eft"), _negated=True),
                            models.Q(("account_number_last4", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="employee_bank_account_eft_has_a_number",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                statutory.models.DateRange(
                                    "active_from",
                                    "active_to",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                            ("employee", "="),
                        ],
                        name="employee_bank_account_no_overlapping_windows",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTaxProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Ten-digit SARS number. Often genuinely absent below the threshold.",
                        max_length=15,
                    ),
                ),
                (
                    "tax_status",
                    models.CharField(
                        choices=[
                            ("standard", "Standard tables"),
                            ("directive_fixed_pct", "Directive — fixed percentage"),
                            ("directive_fixed_amount", "Directive — fixed amount"),
                            ("exempt", "Exempt"),
                            ("foreign", "Foreign"),
                        ],
                        default="standard",
                        max_length=30,
                    ),
                ),
                ("directive_number", models.CharField(blank=True, max_length=30)),
                (
                    "directive_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "directive_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("directive_valid_to", models.DateField(blank=True, null=True)),
                (
                    "medical_scheme_members",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Main member plus dependants, for the medical tax credit.",
                    ),
                ),
                ("is_uif_exempt", models.BooleanField(default=False)),
                (
                    "uif_exempt_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_24_hours_month", "Works under 24 hours a month"),
                            (
                                "foreign_repatriation",
                                "Foreign national to be repatriated",
                            ),
                            ("learner", "Learner under the Skills Development Act"),
                            ("public_servant", "National or provincial public servant"),
                        ],
                        max_length=60,
                    ),
                ),
                ("is_sdl_exempt", models.BooleanField(default=False)),
                (
                    "nature_of_person",
                    models.CharField(
                        choices=[
                            ("A", "A — individual with a South African ID"),
                            ("B", "B — individual without a South African ID"),
                            ("C", "C — director of a private company"),
                        ],
                        default="A",
                        help_text="The SARS code on the IRP5. Defaults from the employee's id_type.",
                        max_length=1,
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_profiles",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_tax_profile",
                "ordering": ["employee_id", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-effective_from"],
                        name="employee_ta_employe_7baef3_idx",
                    ),
                    models.Index(
                        fields=["tenant"], name="employee_ta_tenant__bc765e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "effective_from"),
                        name="uniq_tax_profile_start_per_employee",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("medical_scheme_members__gte", 0)),
                        name="tax_profile_medical_members_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("tax_status", "directive_fixed_pct"), _negated=True
                            ),
                            ("directive_percentage__isnull", False),
                            _connector="OR",
                        ),
                        name="tax_profile_pct_directive_has_a_percentage",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("tax_status", "directive_fixed_amount"), _negated=True
                            ),
                            ("directive_amount__isnull", False),
                            _connector="OR",
                        ),
                        name="tax_profile_amount_directive_has_an_amount",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_uif_exempt", False),
                            models.Q(("uif_exempt_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="tax_profile_uif_exemption_has_a_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="tax_profile_period_ordered",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                statutory.models.DateRange(
                                    "effective_from",
                                    "effective_to",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                            ("employee", "="),
                        ],
                        name="employee_tax_profile_no_overlapping_periods",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workschedule",
            index=models.Index(
                fields=["employee", "-effective_from"],
                name="work_schedu_employe_dcafa5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workschedule",
            index=models.Index(
                fields=["tenant"], name="work_schedu_tenant__fd877d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workschedule",
            constraint=models.UniqueConstraint(
                fields=("employee", "effective_from"),
                name="uniq_schedule_start_per_employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="workschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="work_schedule_period_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="workschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cycle_length_days__gte", 1), ("cycle_length_days__lte", 31)
                ),
                name="work_schedule_cycle_is_a_cycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="workschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("days_per_week__gt", 0), ("days_per_week__lte", 7)),
                name="work_schedule_days_per_week_is_a_week",
            ),
        ),
        migrations.AddConstraint(
            model_name="workschedule",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        statutory.models.DateRange(
                            "effective_from",
                            "effective_to",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("employee", "="),
                ],
                name="work_schedule_no_overlapping_periods",
            ),
        ),
        migrations.AddIndex(
            model_name="workscheduleday",
            index=models.Index(
                fields=["tenant"], name="work_schedu_tenant__afbf28_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workscheduleday",
            constraint=models.UniqueConstraint(
                fields=("work_schedule", "cycle_day"),
                name="uniq_cycle_day_per_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="workscheduleday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ordinary_hours__gte", 0), ("ordinary_hours__lte", 24)
                ),
                name="work_schedule_day_hours_are_a_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="workscheduleday",
            constraint=models.CheckConstraint(
                condition=models.Q(("cycle_day__gte", 0)),
                name="work_schedule_day_is_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workscheduleday",
            constraint=models.CheckConstraint(
                condition=models.Q(("unpaid_break_minutes__gte", 0)),
                name="work_schedule_day_break_is_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workscheduleday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_working_day", True), ("ordinary_hours", 0), _connector="OR"
                ),
                name="work_schedule_day_off_has_no_hours",
            ),
        ),
        migrations.RunSQL(enable_rls("work_schedule"), disable_rls("work_schedule")),
        migrations.RunSQL(enable_rls("work_schedule_day"), disable_rls("work_schedule_day")),
        migrations.RunSQL(
            enable_rls("employee_tax_profile"), disable_rls("employee_tax_profile")
        ),
        migrations.RunSQL(
            enable_rls("employee_bank_account"), disable_rls("employee_bank_account")
        ),
    ]
