# Generated by Django 5.2.17 on 2026-09-14 07:37

import datetime
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import statutory.models
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """The last three employee child tables: entitlements, recurring lines, notes.

    All three are strictly tenant-scoped — every row names a person — so
    ``enable_rls``, never either nullable policy. Without these three ``RunSQL``
    calls the generated isolation suite fails, which is the safety net working: a
    model is covered the day it is written, discovered from the model registry
    rather than from anybody remembering to write a test.

    Depends on ``leave.0001`` because ``employee_leave_entitlement`` points at
    ``leave_type``, which is built in P4 for that reason (D-127).
    """


    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("employees", "0004_schedules_tax_and_banking"),
        ("employers", "0004_payroll_component"),
        ("leave", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLeaveEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_days_per_cycle",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Over and above the statutory figure. Additive.",
                        max_digits=6,
                    ),
                ),
                (
                    "replaces_statutory",
                    models.BooleanField(
                        default=False,
                        help_text="TRUE means the override IS the total, not an addition to it.",
                    ),
                ),
                (
                    "total_days_per_cycle_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="The whole entitlement. Required when replaces_statutory is TRUE.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "accrual_method",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly, straight line"),
                            ("per_days_worked", "One day per 17 days worked"),
                            ("per_hours_worked", "One hour per 17 hours worked"),
                            (
                                "upfront_annual",
                                "Granted in full at the start of the cycle",
                            ),
                        ],
                        default="monthly",
                        max_length=30,
                    ),
                ),
                (
                    "carry_over_max_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="NULL means the statutory forfeiture rule applies.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means current.",
                        null=True,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_entitlements",
                        to="employees.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="leave.leavetype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_leave_entitlement",
                "ordering": ["employee_id", "leave_type_id", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "leave_type", "-effective_from"],
                        name="employee_le_employe_3929fb_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "leave_type", "effective_from"),
                        name="uniq_entitlement_start_per_employee_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("replaces_statutory", False),
                            ("total_days_per_cycle_override__isnull", False),
                            _connector="OR",
                        ),
                        name="entitlement_replacement_states_its_total",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("additional_days_per_cycle__gte", 0)),
                        name="entitlement_addition_is_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("total_days_per_cycle_override__isnull", True),
                            ("total_days_per_cycle_override__gte", 0),
                            _connector="OR",
                        ),
                        name="entitlement_total_is_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("carry_over_max_days__isnull", True),
                            ("carry_over_max_days__gte", 0),
                            _connector="OR",
                        ),
                        name="entitlement_carry_over_is_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "accrual_method__in",
                                [
                                    "monthly",
                                    "per_days_worked",
                                    "per_hours_worked",
                                    "upfront_annual",
                                ],
                            )
                        ),
                        name="entitlement_accrual_method_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="entitlement_period_ordered",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                statutory.models.DateRange(
                                    "effective_from",
                                    "effective_to",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                            ("employee", "="),
                            ("leave_type", "="),
                        ],
                        name="employee_leave_entitlement_no_overlapping_periods",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note_date",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("performance", "Performance"),
                            ("training", "Training"),
                            ("conversation", "Conversation"),
                            ("attendance", "Attendance"),
                        ],
                        default="general",
                        max_length=40,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=150)),
                ("body", models.TextField()),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden from employee self-service. Not a security boundary.",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_note",
                "ordering": ["-note_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-note_date"],
                        name="employee_no_employe_9c5efb_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "category__in",
                                [
                                    "general",
                                    "performance",
                                    "training",
                                    "conversation",
                                    "attendance",
                                ],
                            )
                        ),
                        name="employee_note_category_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("body", ""), _negated=True),
                        name="employee_note_body_is_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeRecurringComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Fixed per period.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "percentage_of_basic",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Alternative to amount.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "balance_outstanding",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Loans and advances. Decremented as each run finalises.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "total_deduction_cap_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="BCEA s34 per-component ceiling, e.g. 10% for accommodation.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means current.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_components",
                        to="employees.employee",
                    ),
                ),
                (
                    "payroll_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_lines",
                        to="employers.payrollcomponent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "written_consent_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="BCEA s34 requires written consent for most deductions.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fileobject",
                    ),
                ),
            ],
            options={
                "db_table": "employee_recurring_component",
                "ordering": ["employee_id", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "is_active"],
                        name="employee_re_employe_3ae1d1_idx",
                    ),
                    models.Index(
                        fields=["tenant", "payroll_component"],
                        name="employee_re_tenant__1e5d67_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__isnull", False),
                            ("percentage_of_basic__isnull", False),
                            _connector="OR",
                        ),
                        name="recurring_component_states_an_amount",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__isnull", True),
                            ("amount__gte", 0),
                            _connector="OR",
                        ),
                        name="recurring_component_amount_is_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("percentage_of_basic__isnull", True),
                            ("percentage_of_basic__gte", 0),
                            _connector="OR",
                        ),
                        name="recurring_component_percentage_is_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("balance_outstanding__isnull", True),
                            ("balance_outstanding__gte", 0),
                            _connector="OR",
                        ),
                        name="recurring_component_balance_is_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("total_deduction_cap_pct__isnull", True),
                            models.Q(
                                ("total_deduction_cap_pct__gt", 0),
                                ("total_deduction_cap_pct__lte", 100),
                            ),
                            _connector="OR",
                        ),
                        name="recurring_component_cap_is_a_percentage",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="recurring_component_period_ordered",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                statutory.models.DateRange(
                                    "effective_from",
                                    "effective_to",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                            ("employee", "="),
                            ("payroll_component", "="),
                        ],
                        name="employee_recurring_component_no_overlapping_periods",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            enable_rls("employee_leave_entitlement"),
            disable_rls("employee_leave_entitlement"),
        ),
        migrations.RunSQL(
            enable_rls("employee_recurring_component"),
            disable_rls("employee_recurring_component"),
        ),
        migrations.RunSQL(enable_rls("employee_note"), disable_rls("employee_note")),
    ]
