# Generated by Django 5.2.17 on 2026-09-14 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Two workbook deviations, recorded together because the split session left both open.

    ``employee_recurring_component`` — D-135, closing O-17's schema half. Sheet 03
    has no overlap constraint here, and the EXCLUDE the abandoned line shipped with
    was wrong for a reason sheet 03 could not state: two advances running at once
    is ordinary, and forbidding it makes an employer invent a second component so
    the deduction can coexist — at which point it stops being recognisable as an
    advance in the BCEA s34 total, a compliance failure no test catches. What the
    EXCLUDE was really standing in for is a line captured twice, so it is replaced
    with a UniqueConstraint over (employee, payroll_component, effective_from,
    amount, percentage_of_basic). ``nulls_distinct=False`` matters because amount
    and percentage_of_basic are mutually exclusive and therefore nullable, and
    NULL = NULL is unknown in PostgreSQL — without it, two rows with the same NULL
    amount would not collide.

    ``employee_leave_entitlement`` — D-136. There is NO operation for it here: the
    EXCLUDE over [effective_from, effective_to) per (employee, leave_type) already
    shipped in ``0005``, ahead of any decision number for it, because the session
    that wrote it reached the same schema judgement the other session reached for
    ``employee_recurring_component`` and reached it correctly. D-136 exists to give
    that already-applied constraint a citation, not to add one — sheet 03 is silent
    on this table too, and asks for exactly this shape on ``employee_position`` and
    ``work_schedule``, which is the deviation's justification. The unique on
    ``effective_from`` alone stops two grants beginning on one day and does nothing
    about a grant back-dated into an open period, which leaves two entitlements in
    force for one leave type with nothing but row order deciding between them.
    """

    dependencies = [
        ("core", "0005_tenantmembership_ui_preferences"),
        ("employees", "0006_current_state_may_outlive_a_termination"),
        ("employers", "0004_payroll_component"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employeerecurringcomponent",
            name="employee_recurring_component_no_overlapping_periods",
        ),
        migrations.AddConstraint(
            model_name="employeerecurringcomponent",
            constraint=models.UniqueConstraint(
                fields=(
                    "employee",
                    "payroll_component",
                    "effective_from",
                    "amount",
                    "percentage_of_basic",
                ),
                name="uniq_recurring_component_line_per_period",
                nulls_distinct=False,
                violation_error_message=(
                    "This line has already been captured for this period — same "
                    "employee, component, start date, amount and percentage. Two "
                    "advances running at once is fine; this is the same advance "
                    "captured twice."
                ),
            ),
        ),
    ]
