# Generated by Django 5.2.17 on 2026-09-14 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """``employee_import_batch`` — D-122, and NOT in the workbook.

    Sheet 02 has only ``attendance_import_batch`` (P5); this table is a
    deliberate addition modelled on it, minus ``period_start``/``period_end`` —
    an employee import has no period the way a month of attendance does.

    An ordinary ``TenantScopedModel`` table, so the plain ``enable_rls`` — no
    shared rows, no system-row lock, nothing this migration needs beyond the
    strict per-tenant policy every employer- and employee-data table carries.

    ``employee.created_by_import_batch`` rides along in the same migration: it
    is the provenance column task 2 asks for, and it cannot exist before this
    table does.
    """

    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0007_recurring_component_and_entitlement_deviations"),
        ("employers", "0004_payroll_component"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_count", models.IntegerField(default=0)),
                ("accepted_count", models.IntegerField(default=0)),
                ("rejected_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("validating", "Validating"),
                            ("preview", "Preview"),
                            ("applied", "Applied"),
                            ("reversed", "Reversed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "validation_report",
                    models.JSONField(
                        default=list,
                        help_text="Per-row errors and warnings. Never a full ID or bank number.",
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_import_batches",
                        to="employers.employer",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "The uploaded spreadsheet. Content is purged once applied or "
                            "reversed (D-141)."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fileobject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_import_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="created_by_import_batch",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Set only by the bulk importer. NULL for a single-capture employee.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees_created",
                to="employees.employeeimportbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeimportbatch",
            index=models.Index(fields=["tenant", "status"], name="employee_im_tenant__52e5e5_idx"),
        ),
        migrations.AddConstraint(
            model_name="employeeimportbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["uploaded", "validating", "preview", "applied", "reversed", "failed"])
                ),
                name="employee_import_batch_status_is_known",
            ),
        ),
        migrations.RunSQL(
            enable_rls("employee_import_batch"), disable_rls("employee_import_batch")
        ),
    ]
