# Generated by Django 5.2.17 on 2026-09-17 06:02

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0008_employeeimportbatch_employee_created_by_import_batch_and_more'),
        ('employers', '0004_payroll_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeenote',
            constraint=models.CheckConstraint(condition=models.Q(('note_date__lte', models.Func(django.db.models.functions.datetime.Now(), output_field=models.DateField(), template="(%(expressions)s AT TIME ZONE 'Africa/Johannesburg')::date"))), name='employee_note_not_dated_in_the_future'),
        ),
        migrations.AddConstraint(
            model_name='employeerecurringcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('percentage_of_basic__isnull', True), ('percentage_of_basic__lte', 100), _connector='OR'), name='recurring_component_percentage_is_a_percentage'),
        ),
    ]
