# Generated by Django 5.2.17 on 2026-09-20 09:20

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import statutory.models
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0012_statutory_method_covers_parental"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeUnionRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("shop_steward", "Shop steward"),
                            ("office_bearer", "Office bearer of a representative trade union"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trade_union_name",
                    models.CharField(
                        blank=True,
                        help_text="The union this role is held in. Free text: the Council's list of representative unions is not reference data this system loads, and a guessed code would be worse than a name somebody typed.",
                        max_length=120,
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, help_text="Exclusive. NULL means current.", null=True
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="union_roles",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_union_role",
                "ordering": ["employee_id", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-effective_from"],
                        name="employee_un_employe_5c4617_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "effective_from"),
                        name="uniq_union_role_start_per_employee",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["shop_steward", "office_bearer"])),
                        name="union_role_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="union_role_period_ordered",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                statutory.models.DateRange(
                                    "effective_from",
                                    "effective_to",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                            ("employee", "="),
                        ],
                        name="employee_union_role_no_overlapping_periods",
                    ),
                ],
            },
        ),
        # An ordinary TenantScopedModel table, so the plain enable_rls - no
        # shared rows and no platform override. In the CREATING migration,
        # because a table that reads as isolated while providing nothing is
        # the failure this codebase has now shipped six times (D-169).
        migrations.RunSQL(enable_rls("employee_union_role"), disable_rls("employee_union_role")),
    ]
