# Generated by Django 5.2.17 on 2026-09-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employeeunionrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerecurringcomponent',
            name='balance_outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Loans and advances: the principal. What is owed is derived (D-303).', max_digits=14, null=True),
        ),
    ]
