# Generated by Django 5.2.17 on 2026-09-25 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0014_recurring_balance_is_the_principal'),
        ('leave', '0014_leaveapplication_expected_date_of_confinement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaveentitlement',
            name='grant_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeleaveentitlement',
            name='granted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeleaveentitlement',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='employeeleaveentitlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grant_reason', ''), ('granted_by_user__isnull', True)), models.Q(('granted_by_user__isnull', False), models.Q(('grant_reason', ''), _negated=True)), _connector='OR'), name='entitlement_grant_is_named_and_reasoned'),
        ),
    ]
