# Generated by Django 5.2.17 on 2026-09-12 22:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from core.db.rls import (
    APPEND_ONLY_FUNCTION,
    DROP_APPEND_ONLY_FUNCTION,
    append_only,
    disable_rls,
    drop_append_only,
    enable_rls,
    enable_rls_optional,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('user_kind', models.CharField(choices=[('platform_superuser', 'Platform superuser'), ('platform_support', 'Platform support'), ('employer', 'Employer'), ('employee_self_service', 'Employee self-service')], db_index=True, default='employer', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=255)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_count', models.SmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reauth_at', models.DateTimeField(blank=True, help_text='Step-up authentication clock. Ownership transfer requires a recent value.', null=True)),
                ('terms_accepted_version', models.CharField(blank=True, max_length=20)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('decimal', 'Decimal'), ('bool', 'Boolean'), ('json', 'JSON'), ('date', 'Date')], default='string', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_secret', models.BooleanField(default=False)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_setting',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trading_name', models.CharField(db_index=True, max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('entity_type', models.CharField(choices=[('private_household', 'Private household'), ('sole_prop', 'Sole proprietor'), ('cc', 'Close corporation'), ('pty_ltd', 'Private company'), ('npo', 'Non-profit'), ('trust', 'Trust'), ('partnership', 'Partnership')], default='private_household', max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('primary_sector_code', models.CharField(blank=True, max_length=30)),
                ('sector_area_code', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(default='ZA', max_length=2)),
                ('default_timezone', models.CharField(default='Africa/Johannesburg', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('onboarding_stage', models.CharField(choices=[('registered', 'Registered'), ('company_setup', 'Company setup'), ('first_employee', 'First employee'), ('first_payroll', 'First payroll'), ('complete', 'Complete')], default='registered', max_length=30)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('data_retention_until', models.DateField(blank=True, help_text='Payroll records retained five years from the last payroll (SARS).', null=True)),
                ('max_admin_users', models.SmallIntegerField(default=2, help_text='Business rule: owner plus one additional user. Data, not a constant.', validators=[django.core.validators.MinValueValidator(1)])),
                ('locale', models.CharField(default='en-ZA', max_length=10)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('document_access', 'Document access'), ('step_up', 'Step-up authentication'), ('mobile_verification', 'Mobile verification')], db_index=True, max_length=30)),
                ('employee_id_ref', models.BigIntegerField(blank=True, null=True)),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Five minutes.')),
                ('attempts', models.SmallIntegerField(default=0, help_text='Locked after five.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('device_token_hash', models.CharField(blank=True, db_index=True, help_text='Trusts the device for 30 days so a payslip view does not cost an SMS (D-13).', max_length=64)),
                ('device_trusted_until', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'otp_challenge',
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('email_attempted', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('bad_password', 'Bad password'), ('unknown_user', 'Unknown user'), ('locked', 'Locked'), ('mfa_failed', 'MFA failed'), ('mfa_success', 'MFA success')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('session_key_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'login_audit',
            },
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('storage_backend', models.CharField(default='s3', max_length=20)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Downloads are blocked until clean.', max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('retention_until', models.DateField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'file_object',
            },
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, max_length=80)),
                ('task_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'background_job',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_kind', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('support', 'Support'), ('api', 'API')], default='user', max_length=20)),
                ('table_name', models.CharField(db_index=True, max_length=64)),
                ('record_pk', models.BigIntegerField(db_index=True)),
                ('operation', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('changed_fields', models.JSONField(default=dict, help_text="{'field': {'old': x, 'new': y}}. Sensitive fields stored as masked markers.")),
                ('business_event', models.CharField(blank=True, db_index=True, max_length=60)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('impersonated_by_user', models.ForeignKey(blank=True, help_text="Set when platform support acts on a tenant's behalf.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tenant')),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_tenant',
            field=models.ForeignKey(blank=True, help_text='Convenience only — where a multi-tenant user last worked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('read_only', 'Read only'), ('employee', 'Employee')], db_index=True, default='admin', max_length=30)),
                ('employee_id_ref', models.BigIntegerField(blank=True, help_text="Becomes a real FK to employee in P4. Set only when role='employee'.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Revoked, never deleted — deleting orphans every created_by_user_id.', null=True)),
                ('access_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Termination date + 2 months for an employee self-service login (D-08).', null=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_membership',
            },
        ),
        migrations.CreateModel(
            name='TenantOwnershipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('initiator_reauth_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True, help_text='72 hours.')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptor_reauth_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_ownership_transfer',
            },
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('read_only', 'Read only'), ('employee', 'Employee')], max_length=30)),
                ('employee_id_ref', models.BigIntegerField(blank=True, null=True)),
                ('token_hash', models.CharField(help_text='SHA-256 of the emailed token. The raw token is never stored.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_invitation',
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='tenant_status_2e0f38_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['trading_name'], name='tenant_trading_fd1139_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('max_admin_users__gte', 1), ('max_admin_users__lte', 5)), name='tenant_max_admin_users_range'),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['mobile_number', '-issued_at'], name='otp_challen_mobile__d1dc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='loginaudit',
            index=models.Index(fields=['user', '-occurred_at'], name='login_audit_user_id_77f307_idx'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['tenant', 'scan_status'], name='file_object_tenant__18d2be_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['status', 'queued_at'], name='background__status_1f780b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', '-occurred_at'], name='audit_log_tenant__742d16_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'record_pk', '-occurred_at'], name='audit_log_table_n_44fea1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['business_event', '-occurred_at'], name='audit_log_busines_1c6edd_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['user_kind'], name='app_user_user_ki_5da4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'role'], name='tenant_memb_tenant__0bf863_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user'], name='tenant_memb_user_id_558eec_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('tenant', 'user'), name='uniq_live_membership_per_tenant_user'),
        ),
        migrations.AddConstraint(
            model_name='tenantownershiptransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='ownership_transfer_distinct_parties'),
        ),
        migrations.AddConstraint(
            model_name='tenantownershiptransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant',), name='uniq_pending_ownership_transfer_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='userinvitation',
            index=models.Index(fields=['tenant', 'email'], name='user_invita_tenant__2cddc5_idx'),
        ),

        # ------------------------------------------------------------------
        # Tenant isolation, layer 2. Django knows nothing about row-level
        # security, so these are hand-added and must be added for every new
        # tenant table. The generated isolation suite fails the build if one
        # is forgotten -- that is the whole point of it.
        #
        # Strict policy: tenant_id NOT NULL, a row is visible to its own
        # tenant and to nothing else. No platform override (decision D-52).
        migrations.RunSQL(enable_rls("tenant_membership"), disable_rls("tenant_membership")),
        migrations.RunSQL(enable_rls("user_invitation"), disable_rls("user_invitation")),
        migrations.RunSQL(
            enable_rls("tenant_ownership_transfer"),
            disable_rls("tenant_ownership_transfer"),
        ),
        migrations.RunSQL(enable_rls("file_object"), disable_rls("file_object")),
        # Optional policy: tenant_id nullable because the row may predate the
        # tenant being known (decision D-53). A tenant session still never sees
        # the NULL-tenant rows; a session with no tenant pinned sees only those.
        migrations.RunSQL(enable_rls_optional("otp_challenge"), disable_rls("otp_challenge")),
        migrations.RunSQL(enable_rls_optional("login_audit"), disable_rls("login_audit")),
        migrations.RunSQL(enable_rls_optional("audit_log"), disable_rls("audit_log")),
        migrations.RunSQL(enable_rls_optional("background_job"), disable_rls("background_job")),
        # ------------------------------------------------------------------
        # Invariant 4: the audit trail is append-only. A trigger, not a
        # REVOKE -- the application connects as the table owner, and an owner
        # is not bound by a revoke against PUBLIC.
        migrations.RunSQL(APPEND_ONLY_FUNCTION, DROP_APPEND_ONLY_FUNCTION),
        migrations.RunSQL(append_only("audit_log"), drop_append_only("audit_log")),
    ]
