# Generated by Django 5.2.17 on 2026-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_audit_read_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmembership",
            name="ui_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="This person's view choices in this tenant. Never anything that decides a figure (D-133).",
            ),
        ),
    ]
