# Generated by Django 5.2.17 on 2026-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenantmembership_ui_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileobject',
            name='content_purged_at',
            field=models.DateTimeField(blank=True, help_text='Bytes deleted, row kept for the trail. Never downloadable again.', null=True),
        ),
    ]
