# Generated by Django 5.2.17 on 2026-09-13 00:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_label', models.CharField(help_text="e.g. 'REF-2026.03.01'.", max_length=40, unique=True)),
                ('applies_from', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True, help_text='What changed, and why.')),
                ('loaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 of the loaded fixture set, so a silently edited fixture is detectable.', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('golden_tests_passed', models.BooleanField(default=False, help_text='The published SARS and DEL worked examples reproduce exactly against this version. A version that fails is never in force.')),
                ('data_current_through', models.DateField(blank=True, db_index=True, help_text='THE STALENESS GUARD. The last date the statutory data is confirmed correct for. A payroll run whose period ends after this is blocked rather than computed against figures nobody has checked.', null=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reference_data_version',
                'indexes': [models.Index(fields=['data_current_through'], name='reference_d_data_cu_3d4567_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_current_through__isnull', True), ('data_current_through__gte', models.F('applies_from')), _connector='OR'), name='ref_version_current_through_after_applies_from'), models.CheckConstraint(condition=models.Q(('data_current_through__isnull', True), ('verified_at__isnull', False), _connector='OR'), name='ref_version_current_through_requires_verification'), models.CheckConstraint(condition=models.Q(models.Q(('verified_at__isnull', True), ('verified_by_user__isnull', True)), models.Q(('verified_at__isnull', False), ('verified_by_user__isnull', False)), _connector='OR'), name='ref_version_verified_by_and_at_together')],
            },
        ),
        migrations.CreateModel(
            name='StatutoryWatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watch_code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='What to look for, and how to recognise that it has changed.')),
                ('change_cadence', models.CharField(choices=[('annual_1_march', 'Annual, effective 1 March'), ('annual_1_may', 'Annual, effective 1 May'), ('irregular', 'Irregular'), ('as_proclaimed', 'As proclaimed')], db_index=True, default='annual_1_march', max_length=30)),
                ('typical_publication_window', models.CharField(blank=True, help_text="e.g. 'late January to mid February'.", max_length=60)),
                ('next_expected_date', models.DateField(blank=True, db_index=True, help_text='NULL for genuinely unpredictable items, which are swept quarterly instead.', null=True)),
                ('last_confirmed_date', models.DateField(blank=True, help_text="When someone last checked this against the source, whether or not it had changed. A 'no change' answer still advances this — the record that the check happened matters as much as the change.", null=True)),
                ('last_change_effective_date', models.DateField(blank=True, null=True)),
                ('source_name', models.CharField(help_text="e.g. 'Department of Employment and Labour gazette'.", max_length=150)),
                ('source_url', models.URLField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('current', 'Current'), ('due', 'Due'), ('overdue', 'Overdue'), ('change_published_not_loaded', 'Change published, not loaded')], db_index=True, default='current', max_length=30)),
                ('responsible_role', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_confirmed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'statutory_watch_item',
                'indexes': [models.Index(fields=['next_expected_date'], name='statutory_w_next_ex_0c1097_idx'), models.Index(fields=['status'], name='statutory_w_status_1242db_idx')],
            },
        ),
    ]
