# Generated by Django 5.2.17 on 2026-09-13 00:21

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
import statutory.models
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    """Sectors, areas, job grades and the minimum wage table.

    Hand-added: BtreeGistExtension. The exclusion constraint that forbids
    overlapping wage periods builds a GiST index, and GiST needs btree_gist to
    support the `=` operator on plain scalar columns (sector_id, hours_band).
    Without it this migration fails with "data type bigint has no default operator
    class for access method gist".

    It has to be a migration operation rather than a one-off psql command, because
    pytest creates test_labourmax from template1 on every run and CI builds its
    database from scratch. Installing an extension by hand into one database is how
    a constraint ends up existing in development and missing in production.

    btree_gist is a trusted extension in PostgreSQL 13+, so the database owner can
    create it without superuser rights - which matters, because the application role
    deliberately is not one.
    """

    dependencies = [
        ('statutory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('DOMESTIC', 'Domestic worker sector'), ('CONTRACT_CLEANING', 'Contract cleaning sector')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('determination_reference', models.CharField(blank=True, help_text="e.g. 'Sectoral Determination 7' or 'Sectoral Determination 1'.", max_length=120)),
                ('uses_area_rates', models.BooleanField(default=False, help_text='True for contract cleaning, where the minimum differs by geographic area.')),
                ('has_statutory_annual_bonus', models.BooleanField(default=False, help_text="True for contract cleaning: 4.333 weeks' remuneration, accrued monthly.")),
                ('has_provident_fund', models.BooleanField(default=False, help_text='True for contract cleaning, via the bargaining council.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_grades', to='statutory.sector')),
            ],
            options={
                'db_table': 'job_grade',
                'ordering': ['sector_id', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SectorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='AREA_A | AREA_B_KZN | AREA_C', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Which councils and metros are included.')),
                ('uses_bargaining_council_rates', models.BooleanField(default=False, help_text='True for KwaZulu-Natal: rates come from the BCCCI collective agreement.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='statutory.sector')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sector_area',
            },
        ),
        migrations.CreateModel(
            name='MunicipalityAreaMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, help_text='Exclusive. NULL means currently in force.', null=True)),
                ('province_code', models.CharField(db_index=True, help_text='GP|WC|KZN|EC|FS|MP|LP|NW|NC', max_length=10)),
                ('municipality_name', models.CharField(db_index=True, max_length=120)),
                ('municipality_type', models.CharField(choices=[('metro', 'Metropolitan municipality'), ('district', 'District municipality'), ('local', 'Local municipality')], default='local', max_length=20)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sector_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipalities', to='statutory.sectorarea')),
            ],
            options={
                'db_table': 'municipality_area_map',
            },
        ),
        migrations.CreateModel(
            name='MinimumWageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, help_text='Exclusive. NULL means currently in force.', null=True)),
                ('source_reference', models.CharField(help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.", max_length=200)),
                ('source_url', models.URLField(blank=True, help_text='Optional. Not every gazette is online, and a fabricated link is worse than none.', max_length=400)),
                ('notes', models.TextField(blank=True, help_text='Interpretation notes — how the figure was read, and anything ambiguous about it.')),
                ('hours_band', models.CharField(choices=[('all', 'All hours'), ('lte_27_hours', '27 ordinary hours per week or fewer'), ('gt_27_hours', 'More than 27 ordinary hours per week')], default='all', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=4, help_text='The authoritative figure. Four decimals: gazettes publish rates like 30.2300.', max_digits=10)),
                ('weekly_rate_45h', models.DecimalField(blank=True, decimal_places=2, help_text='As gazetted, not recomputed. Gazettes round.', max_digits=12, null=True)),
                ('monthly_rate_45h', models.DecimalField(blank=True, decimal_places=2, help_text='As gazetted.', max_digits=12, null=True)),
                ('daily_rate_9h', models.DecimalField(blank=True, decimal_places=2, help_text='As gazetted.', max_digits=12, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_grade', models.ForeignKey(blank=True, help_text='NULL = applies to every grade in the sector.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minimum_wages', to='statutory.jobgrade')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, help_text='NULL = the general National Minimum Wage.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minimum_wages', to='statutory.sector')),
                ('sector_area', models.ForeignKey(blank=True, help_text='NULL when the sector does not use area rates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minimum_wages', to='statutory.sectorarea')),
            ],
            options={
                'db_table': 'minimum_wage_rate',
            },
        ),
        migrations.AddConstraint(
            model_name='jobgrade',
            constraint=models.UniqueConstraint(fields=('sector', 'code'), name='uniq_job_grade_per_sector'),
        ),
        migrations.AddConstraint(
            model_name='sectorarea',
            constraint=models.UniqueConstraint(fields=('sector', 'code'), name='uniq_area_code_per_sector'),
        ),
        migrations.AddIndex(
            model_name='municipalityareamap',
            index=models.Index(fields=['province_code', 'municipality_name'], name='municipalit_provinc_030c6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='municipalityareamap',
            constraint=models.UniqueConstraint(fields=('municipality_name', 'effective_from'), name='uniq_municipality_mapping_per_date'),
        ),
        migrations.AddConstraint(
            model_name='municipalityareamap',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='municipality_area_map_effective_range_ordered'),
        ),
        migrations.AddIndex(
            model_name='minimumwagerate',
            index=models.Index(fields=['effective_from', 'effective_to'], name='minimum_wag_effecti_008f7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='minimumwagerate',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate__gt', 0)), name='minimum_wage_rate_hourly_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='minimumwagerate',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='minimum_wage_rate_effective_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='minimumwagerate',
            constraint=models.CheckConstraint(condition=models.Q(('source_reference', ''), _negated=True), name='minimum_wage_rate_source_reference_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='minimumwagerate',
            constraint=models.UniqueConstraint(fields=('sector', 'sector_area', 'job_grade', 'hours_band', 'effective_from'), name='uniq_minimum_wage_scope_per_date', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='minimumwagerate',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(statutory.models.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), (django.db.models.functions.comparison.Coalesce('sector', models.Value(0)), '='), (django.db.models.functions.comparison.Coalesce('sector_area', models.Value(0)), '='), (django.db.models.functions.comparison.Coalesce('job_grade', models.Value(0)), '='), ('hours_band', '=')], name='minimum_wage_rate_no_overlapping_periods'),
        ),
    ]
