# Generated by Django 5.2.17 on 2026-09-13 07:49

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
import statutory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """PAYE, the scalar parameters, the three rule sets, holidays, source codes and banks.

    The rest of P2's tables. Nothing here is tenant-scoped: statutory reference data
    is the same for every employer in the country, so these tables carry no `tenant`
    column and no row-level security policy. That is deliberate and is the only
    category of table in the schema for which it is true - see D-54.

    No `BtreeGistExtension` operation this time. It is already installed by 0002 and
    the three exclusion constraints here (statutory_parameter and the two rule sets
    that key on `sector`) rely on it being there.

    Every statutory *value* is absent from this migration on purpose. Column defaults
    for BCEA figures - 15 annual leave days, a 1.5 overtime multiplier - would put a
    statutory number in a migration, which is the one thing CLAUDE.md forbids
    outright, and would let an unverified figure enter the database wearing the
    citation of a row that never covered it.
    """

    dependencies = [
        ("statutory", "0002_sector_jobgrade_sectorarea_municipalityareamap_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("universal_branch_code", models.CharField(blank=True, max_length=10)),
                ("bic_swift", models.CharField(blank=True, max_length=11)),
                ("account_number_min_length", models.SmallIntegerField()),
                ("account_number_max_length", models.SmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "bank",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "account_number_max_length__gte",
                                models.F("account_number_min_length"),
                            )
                        ),
                        name="bank_account_length_bounds_ordered",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. '2026/2027'.", max_length=12, unique=True
                    ),
                ),
                ("start_date", models.DateField(help_text="1 March.", unique=True)),
                ("end_date", models.DateField(help_text="End of February.")),
                (
                    "is_open",
                    models.BooleanField(
                        default=True,
                        help_text="Closed once IRP5 submission for the year is finalised.",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tax_year",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SarsSourceCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. 3601, 3605, 3699, 4141.",
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "code_group",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("allowance", "Allowance"),
                            ("fringe_benefit", "Fringe benefit"),
                            ("deduction", "Deduction"),
                            ("employer_contribution", "Employer contribution"),
                            ("total", "Total"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                (
                    "is_uif_remuneration",
                    models.BooleanField(
                        default=True,
                        help_text="Part of the UIF contribution base. Commission is NOT.",
                    ),
                ),
                ("is_sdl_remuneration", models.BooleanField(default=True)),
                ("is_coida_remuneration", models.BooleanField(default=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valid_from_tax_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="statutory.taxyear",
                    ),
                ),
                (
                    "valid_to_tax_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="statutory.taxyear",
                    ),
                ),
            ],
            options={
                "db_table": "sars_source_code",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PayeTaxBracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_reference",
                    models.CharField(
                        help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Not every gazette is online, and a fabricated link is worse than none.",
                        max_length=400,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interpretation notes — how the figure was read, and anything ambiguous about it.",
                    ),
                ),
                (
                    "bracket_order",
                    models.SmallIntegerField(help_text="1..n, lowest band first."),
                ),
                (
                    "income_from",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Inclusive lower bound of annual taxable income.",
                        max_digits=14,
                    ),
                ),
                (
                    "income_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Inclusive upper bound. NULL = the top bracket.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "base_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cumulative tax at income_from, as printed by SARS.",
                        max_digits=14,
                    ),
                ),
                (
                    "marginal_rate_pct",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Percent, e.g. 26.000.",
                        max_digits=6,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tax_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brackets",
                        to="statutory.taxyear",
                    ),
                ),
            ],
            options={
                "db_table": "paye_tax_bracket",
                "ordering": ["tax_year_id", "bracket_order"],
            },
        ),
        migrations.CreateModel(
            name="PayeRebate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_reference",
                    models.CharField(
                        help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Not every gazette is online, and a fabricated link is worse than none.",
                        max_length=400,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interpretation notes — how the figure was read, and anything ambiguous about it.",
                    ),
                ),
                (
                    "rebate_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary (65 and over)"),
                            ("tertiary", "Tertiary (75 and over)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_age",
                    models.SmallIntegerField(default=0, help_text="0, 65 or 75."),
                ),
                (
                    "annual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="This tier only. The calculator sums the tiers.",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_threshold_annual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual income below which no PAYE is due.",
                        max_digits=12,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tax_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebates",
                        to="statutory.taxyear",
                    ),
                ),
            ],
            options={
                "db_table": "paye_rebate",
                "ordering": ["tax_year_id", "min_age"],
            },
        ),
        migrations.CreateModel(
            name="MedicalTaxCreditRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_reference",
                    models.CharField(
                        help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Not every gazette is online, and a fabricated link is worse than none.",
                        max_length=400,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interpretation notes — how the figure was read, and anything ambiguous about it.",
                    ),
                ),
                (
                    "main_member_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "first_dependant_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "additional_dependant_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tax_year",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_tax_credit",
                        to="statutory.taxyear",
                    ),
                ),
            ],
            options={
                "db_table": "medical_tax_credit_rate",
            },
        ),
        migrations.CreateModel(
            name="TerminationRuleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means currently in force.",
                        null=True,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Not every gazette is online, and a fabricated link is worse than none.",
                        max_length=400,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interpretation notes — how the figure was read, and anything ambiguous about it.",
                    ),
                ),
                (
                    "notice_weeks_under_6_months",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "notice_weeks_6_months_and_over",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "notice_weeks_over_1_year",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "severance_weeks_per_completed_year",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "severance_requires_operational_reason",
                    models.BooleanField(
                        help_text="Severance is a retrenchment entitlement, not a general one."
                    ),
                ),
                (
                    "annual_bonus_weeks",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Contract cleaning: 4.333 weeks under SD1.",
                        max_digits=6,
                    ),
                ),
                (
                    "annual_bonus_month",
                    models.SmallIntegerField(
                        help_text="Calendar month of normal payment."
                    ),
                ),
                ("annual_bonus_pro_rata_on_termination", models.BooleanField()),
                ("annual_bonus_min_service_months", models.SmallIntegerField()),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = the BCEA default, used where a sectoral determination is silent.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="statutory.sector",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "termination_rule_set",
            },
        ),
        migrations.CreateModel(
            name="WorkingTimeRuleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means currently in force.",
                        null=True,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Not every gazette is online, and a fabricated link is worse than none.",
                        max_length=400,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interpretation notes — how the figure was read, and anything ambiguous about it.",
                    ),
                ),
                (
                    "ordinary_hours_per_week",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "ordinary_hours_per_day_5day",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "ordinary_hours_per_day_6day",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "overtime_multiplier",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "max_overtime_hours_per_day",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "max_overtime_hours_per_week",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "sunday_multiplier_non_ordinary",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "sunday_multiplier_ordinary",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "public_holiday_worked_multiplier",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "public_holiday_not_worked_paid",
                    models.BooleanField(
                        help_text="Paid when the holiday falls on a day the employee would ordinarily work."
                    ),
                ),
                (
                    "night_work_start_time",
                    models.TimeField(help_text="BCEA s17 night-work window."),
                ),
                ("night_work_end_time", models.TimeField()),
                (
                    "night_allowance_type",
                    models.CharField(
                        help_text="percentage | fixed_amount | time_off", max_length=20
                    ),
                ),
                (
                    "night_allowance_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Percent of hourly rate, or rand per shift.",
                        max_digits=10,
                    ),
                ),
                (
                    "standby_allowance_per_shift",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="SD7 night standby allowance. Gazetted, escalates.",
                        max_digits=10,
                    ),
                ),
                ("standby_window_start", models.TimeField()),
                ("standby_window_end", models.TimeField()),
                (
                    "standby_hours_before_overtime",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual work beyond this within a standby shift attracts overtime.",
                        max_digits=5,
                    ),
                ),
                (
                    "min_paid_hours_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="SD1 guarantees paid hours if an employee is called in.",
                        max_digits=5,
                    ),
                ),
                (
                    "meal_interval_after_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("meal_interval_minutes", models.SmallIntegerField()),
                ("daily_rest_hours", models.SmallIntegerField()),
                ("weekly_rest_hours", models.SmallIntegerField()),
                (
                    "accommodation_deduction_max_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="SD7 permitted accommodation deduction.",
                        max_digits=5,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = the BCEA default, used where a sectoral determination is silent.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="statutory.sector",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "working_time_rule_set",
            },
        ),
        migrations.CreateModel(
            name="BankBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_code", models.CharField(max_length=10)),
                ("branch_name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="statutory.bank",
                    ),
                ),
            ],
            options={
                "db_table": "bank_branch",
                "ordering": ["bank_id", "branch_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bank", "branch_code"), name="uniq_branch_code_per_bank"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaveRuleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means currently in force.",
                        null=True,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Not every gazette is online, and a fabricated link is worse than none.",
                        max_length=400,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interpretation notes — how the figure was read, and anything ambiguous about it.",
                    ),
                ),
                (
                    "annual_leave_days_per_cycle_5day",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Working days per cycle on a 5-day week.",
                        max_digits=6,
                    ),
                ),
                (
                    "annual_leave_days_per_cycle_6day",
                    models.DecimalField(decimal_places=3, max_digits=6),
                ),
                (
                    "annual_accrual_days_per_month_5day",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Straight-line monthly accrual.",
                        max_digits=6,
                    ),
                ),
                (
                    "annual_accrual_days_per_month_6day",
                    models.DecimalField(decimal_places=3, max_digits=6),
                ),
                (
                    "annual_accrual_ratio_days_worked",
                    models.SmallIntegerField(
                        help_text="One day per N days worked — the written-agreement alternative."
                    ),
                ),
                (
                    "annual_accrual_ratio_hours_worked",
                    models.SmallIntegerField(help_text="One hour per N hours worked."),
                ),
                ("annual_leave_cycle_months", models.SmallIntegerField()),
                (
                    "annual_leave_forfeit_months",
                    models.SmallIntegerField(
                        help_text="Leave must be taken within N months of cycle end."
                    ),
                ),
                ("annual_leave_payable_on_termination", models.BooleanField()),
                ("sick_leave_cycle_months", models.SmallIntegerField()),
                (
                    "sick_leave_weeks_equivalent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Entitlement expressed in weeks of days normally worked.",
                        max_digits=5,
                    ),
                ),
                (
                    "sick_leave_first_six_months_ratio",
                    models.SmallIntegerField(
                        help_text="One day per N days worked during the first six months of employment."
                    ),
                ),
                ("sick_leave_payable_on_termination", models.BooleanField()),
                (
                    "family_responsibility_days",
                    models.SmallIntegerField(help_text="Per 12-month cycle."),
                ),
                ("family_resp_min_service_months", models.SmallIntegerField()),
                ("family_resp_min_days_per_week", models.SmallIntegerField()),
                ("parental_leave_total_days", models.SmallIntegerField()),
                ("parental_leave_shareable", models.BooleanField()),
                (
                    "maternity_pre_birth_reserved_days",
                    models.SmallIntegerField(
                        help_text="Days reserved to the birth mother, if any."
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = the BCEA default, used where a sectoral determination is silent.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="statutory.sector",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_rule_set",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="leave_rule_set_effective_range_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_reference", ""), _negated=True),
                        name="leave_rule_set_source_reference_not_blank",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                statutory.models.DateRange(
                                    "effective_from",
                                    "effective_to",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                            (
                                django.db.models.functions.comparison.Coalesce(
                                    "sector", models.Value(0)
                                ),
                                "=",
                            ),
                        ],
                        name="leave_rule_set_no_overlapping_periods",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_reference",
                    models.CharField(
                        help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Not every gazette is online, and a fabricated link is worse than none.",
                        max_length=400,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interpretation notes — how the figure was read, and anything ambiguous about it.",
                    ),
                ),
                ("holiday_date", models.DateField(db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("country_code", models.CharField(default="ZA", max_length=2)),
                (
                    "is_statutory",
                    models.BooleanField(
                        default=True,
                        help_text="False for once-off proclaimed days: elections, mourning.",
                    ),
                ),
                (
                    "shifted_from_date",
                    models.DateField(
                        blank=True,
                        help_text="The Sunday this holiday moved from, where the Act's Monday rule applied.",
                        null=True,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "public_holiday",
                "ordering": ["holiday_date"],
                "indexes": [
                    models.Index(
                        fields=["holiday_date"], name="public_holi_holiday_a5a857_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "holiday_date"),
                        name="uniq_public_holiday_per_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("shifted_from_date__isnull", True),
                            ("shifted_from_date__lt", models.F("holiday_date")),
                            _connector="OR",
                        ),
                        name="public_holiday_shifted_from_is_earlier",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_reference", ""), _negated=True),
                        name="public_holiday_source_reference_not_blank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StatutoryParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Exclusive. NULL means currently in force.",
                        null=True,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Not every gazette is online, and a fabricated link is worse than none.",
                        max_length=400,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interpretation notes — how the figure was read, and anything ambiguous about it.",
                    ),
                ),
                (
                    "parameter_code",
                    models.CharField(
                        db_index=True,
                        help_text="UIF_EMPLOYEE_RATE_PCT, UIF_MONTHLY_CEILING, SDL_RATE_PCT, SDL_ANNUAL_EXEMPTION, COIDA_ANNUAL_CEILING, BCEA_EARNINGS_THRESHOLD, VAT_RATE_PCT, LEAVE_ACCRUAL_DIVISOR_DAYS",
                        max_length=60,
                    ),
                ),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Never a float.",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "value_text",
                    models.CharField(
                        blank=True,
                        help_text="For the rare non-numeric parameter.",
                        max_length=200,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("ZAR", "Rand"),
                            ("percent", "Percent"),
                            ("days", "Days"),
                            ("hours", "Hours"),
                            ("ratio", "Ratio"),
                            ("weeks", "Weeks"),
                        ],
                        default="ZAR",
                        max_length=20,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "statutory_parameter",
                "ordering": ["parameter_code", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["parameter_code", "-effective_from"],
                        name="statutory_p_paramet_20d093_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parameter_code", "effective_from"),
                        name="uniq_statutory_parameter_per_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("value_numeric__isnull", False),
                            models.Q(("value_text", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="statutory_parameter_has_a_value",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="statutory_parameter_effective_range_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_reference", ""), _negated=True),
                        name="statutory_parameter_source_reference_not_blank",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                statutory.models.DateRange(
                                    "effective_from",
                                    "effective_to",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                            ("parameter_code", "="),
                        ],
                        name="statutory_parameter_no_overlapping_periods",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="taxyear",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="tax_year_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="sarssourcecode",
            index=models.Index(
                fields=["code_group"], name="sars_source_code_gr_e891c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payetaxbracket",
            index=models.Index(
                fields=["tax_year", "income_from"],
                name="paye_tax_br_tax_yea_ac8e24_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payetaxbracket",
            constraint=models.UniqueConstraint(
                fields=("tax_year", "bracket_order"),
                name="uniq_bracket_order_per_tax_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="payetaxbracket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("income_to__isnull", True),
                    ("income_to__gt", models.F("income_from")),
                    _connector="OR",
                ),
                name="paye_bracket_income_range_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="payetaxbracket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("marginal_rate_pct__gte", 0), ("marginal_rate_pct__lte", 100)
                ),
                name="paye_bracket_marginal_rate_is_a_percentage",
            ),
        ),
        migrations.AddConstraint(
            model_name="payetaxbracket",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_tax__gte", 0), ("income_from__gte", 0)),
                name="paye_bracket_amounts_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payetaxbracket",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                name="paye_tax_bracket_source_reference_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="payerebate",
            constraint=models.UniqueConstraint(
                fields=("tax_year", "rebate_type"), name="uniq_rebate_type_per_tax_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="payerebate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("annual_amount__gte", 0), ("tax_threshold_annual__gte", 0)
                ),
                name="paye_rebate_amounts_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payerebate",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                name="paye_rebate_source_reference_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicaltaxcreditrate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("additional_dependant_monthly__gte", 0),
                    ("first_dependant_monthly__gte", 0),
                    ("main_member_monthly__gte", 0),
                ),
                name="medical_credit_amounts_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicaltaxcreditrate",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                name="medical_tax_credit_rate_source_reference_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminationruleset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="termination_rule_set_effective_range_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminationruleset",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                name="termination_rule_set_source_reference_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminationruleset",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        statutory.models.DateRange(
                            "effective_from",
                            "effective_to",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    (
                        django.db.models.functions.comparison.Coalesce(
                            "sector", models.Value(0)
                        ),
                        "=",
                    ),
                ],
                name="termination_rule_set_no_overlapping_periods",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminationruleset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("annual_bonus_month__gte", 1), ("annual_bonus_month__lte", 12)
                ),
                name="termination_annual_bonus_month_is_a_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="workingtimeruleset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="working_time_rule_set_effective_range_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="workingtimeruleset",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                name="working_time_rule_set_source_reference_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="workingtimeruleset",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        statutory.models.DateRange(
                            "effective_from",
                            "effective_to",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    (
                        django.db.models.functions.comparison.Coalesce(
                            "sector", models.Value(0)
                        ),
                        "=",
                    ),
                ],
                name="working_time_rule_set_no_overlapping_periods",
            ),
        ),
        migrations.AddConstraint(
            model_name="workingtimeruleset",
            constraint=models.CheckConstraint(
                condition=models.Q(("overtime_multiplier__gte", 1)),
                name="working_time_overtime_multiplier_at_least_one",
            ),
        ),
    ]
