# Generated by Django 5.2.17 on 2026-09-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statutory", "0003_bank_taxyear_sarssourcecode_payetaxbracket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorarea",
            name="code",
            field=models.CharField(
                help_text="AREA_A | AREA_B | AREA_C_KZN", max_length=20
            ),
        ),
    ]
