# Generated by Django 5.2.17 on 2026-09-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    """A bank's account number length may be unknown, and NULL says so.

    Per-bank account number lengths are operational data - they come from the banks
    and from the ACB specification, not from one authoritative published list. The
    columns were NOT NULL, which meant loading any bank at all required inventing two
    numbers for it.

    A guessed bound is worse than none. Too narrow and it rejects a valid account
    number, which reads as a system fault to the employer and ends with an employee
    not being paid on the 25th; too wide and it validates nothing while appearing to.
    So NULL now means "nobody has confirmed this bank's rule", validation falls back
    to the general nine-to-eleven digit range, and a bank whose rule someone HAS
    confirmed carries it.

    A second CHECK keeps the two bounds together: one without the other is a
    half-loaded rule that looks like a working one.

    Bank also gains ``notes``, because the branch code's provenance has to live
    somewhere and Bank is deliberately not a cited statutory model - a universal
    branch code is published by the bank, not gazetted, and demanding a statutory
    citation for one invites a fabricated citation.
    """


    dependencies = [
        ("statutory", "0006_sars_source_code_citations"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bank",
            name="bank_account_length_bounds_ordered",
        ),
        migrations.AddField(
            model_name="bank",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Where the branch code came from, and anything odd about this bank.",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="account_number_max_length",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bank",
            name="account_number_min_length",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="bank",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("account_number_min_length__isnull", True),
                    ("account_number_max_length__isnull", True),
                    (
                        "account_number_max_length__gte",
                        models.F("account_number_min_length"),
                    ),
                    _connector="OR",
                ),
                name="bank_account_length_bounds_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="bank",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("account_number_max_length__isnull", True),
                        ("account_number_min_length__isnull", True),
                    ),
                    models.Q(
                        ("account_number_max_length__isnull", False),
                        ("account_number_min_length__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="bank_account_length_bounds_together",
            ),
        ),
    ]
