# Generated by Django 5.2.17 on 2026-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statutory", "0008_reference_tables_refuse_deletes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statutoryparameter",
            name="parameter_code",
            field=models.CharField(
                db_index=True,
                help_text="UIF_EMPLOYEE_RATE_PCT, UIF_MONTHLY_CEILING, SDL_RATE_PCT, SDL_ANNUAL_EXEMPTION, COIDA_ANNUAL_CEILING, BCEA_EARNINGS_THRESHOLD, VAT_RATE_PCT, LEAVE_ACCRUAL_DIVISOR_DAYS, MINIMUM_EMPLOYMENT_AGE",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="statutoryparameter",
            name="unit",
            field=models.CharField(
                choices=[
                    ("ZAR", "Rand"),
                    ("percent", "Percent"),
                    ("days", "Days"),
                    ("hours", "Hours"),
                    ("ratio", "Ratio"),
                    ("weeks", "Weeks"),
                    ("years", "Years"),
                ],
                default="ZAR",
                max_length=20,
            ),
        ),
    ]
