# Generated by Django 5.2.17 on 2026-09-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statutory", "0009_parameter_unit_years"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorarea",
            name="code",
            field=models.CharField(
                help_text="AREA_A (listed Metropolitan and Local Councils) | AREA_B (KwaZulu-Natal, BCCCI) | AREA_C (rest of the RSA)",
                max_length=20,
            ),
        ),
    ]
