# Generated by Django 5.2.17 on 2026-09-14 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """D-68 closed: notice bands carry their own units, and SD1 splits at four
    weeks of service.

    The three ``notice_weeks_*`` buckets on ``termination_rule_set`` cannot
    express SD1's boundary at four weeks, nor its unit — clause 23(1)(a)
    states one WORKING DAY, and a bare number would have to guess a working
    week. Nothing reads the three columns (P7's termination engine does not
    exist yet), so they are dropped in the same migration that adds their
    replacement rather than left "deprecated" — two sources for one
    compliance answer is the D-89 failure mode.

    ``termination_notice_band`` is a cited child of the rule set, the same
    shape as ``paye_tax_bracket`` under ``tax_year``. No RLS wiring: like
    every other statutory reference table, it carries no tenant and no
    shared-catalogue flag — it is platform data, read by everyone, owned by
    no one.
    """

    dependencies = [
        ("statutory", "0010_alter_sectorarea_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terminationruleset",
            name="notice_weeks_6_months_and_over",
        ),
        migrations.RemoveField(
            model_name="terminationruleset",
            name="notice_weeks_over_1_year",
        ),
        migrations.RemoveField(
            model_name="terminationruleset",
            name="notice_weeks_under_6_months",
        ),
        migrations.CreateModel(
            name="TerminationNoticeBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_reference",
                    models.CharField(
                        help_text=(
                            "Where this figure comes from, precisely enough to find it "
                            "again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI "
                            "Collective Agreement 2026, cl 8'."
                        ),
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text=(
                            "Optional. Not every gazette is online, and a fabricated link "
                            "is worse than none."
                        ),
                        max_length=400,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Interpretation notes — how the figure was read, and anything "
                            "ambiguous about it."
                        ),
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(help_text="1..n, shortest service first."),
                ),
                ("service_from_value", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "service_from_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "service_to_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="NULL = open-ended.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "service_to_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notice_value", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "notice_unit",
                    models.CharField(
                        choices=[("days", "Days"), ("weeks", "Weeks")], max_length=10
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "termination_rule_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notice_bands",
                        to="statutory.terminationruleset",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "termination_notice_band",
                "ordering": ["termination_rule_set_id", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["termination_rule_set"], name="termination_termina_fbbb36_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("termination_rule_set", "sequence"),
                        name="uniq_notice_band_sequence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("service_from_value__gte", 0)),
                        name="termination_notice_band_service_from_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("service_to_value__isnull", True),
                            ("service_to_value__gt", 0),
                            _connector="OR",
                        ),
                        name="termination_notice_band_service_to_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("notice_value__gt", 0)),
                        name="termination_notice_band_notice_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("service_to_unit", ""), ("service_to_value__isnull", True)
                            ),
                            models.Q(
                                ("service_to_unit__in", ["days", "weeks", "months", "years"]),
                                ("service_to_value__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="termination_notice_band_service_to_paired",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("service_from_unit__in", ["days", "weeks", "months", "years"])
                        ),
                        name="termination_notice_band_service_from_unit_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("notice_unit__in", ["days", "weeks"])),
                        name="termination_notice_band_notice_unit_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_reference", ""), _negated=True),
                        name="termination_notice_band_source_reference_not_blank",
                    ),
                ],
            },
        ),
    ]
