# Generated by Django 5.2.17 on 2026-09-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statutory", "0012_notice_band_inclusivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statutoryparameter",
            name="unit",
            field=models.CharField(
                choices=[
                    ("ZAR", "Rand"),
                    ("percent", "Percent"),
                    ("days", "Days"),
                    ("hours", "Hours"),
                    ("ratio", "Ratio"),
                    ("weeks", "Weeks"),
                    ("months", "Months"),
                    ("years", "Years"),
                ],
                default="ZAR",
                max_length=20,
            ),
        ),
    ]
