# Generated by Django 5.2.17 on 2026-09-17 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0014_accommodation_cap_pair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedataversion',
            name='supersede_reason',
            field=models.TextField(blank=True, help_text='Why it was re-encoded. Mandatory when superseding.'),
        ),
        migrations.AddField(
            model_name='referencedataversion',
            name='supersedes',
            field=models.OneToOneField(blank=True, help_text='The version this one re-encodes. Never a figure change - see the loader.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='statutory.referencedataversion'),
        ),
        migrations.AddConstraint(
            model_name='referencedataversion',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', True), models.Q(('supersede_reason', ''), _negated=True), _connector='OR'), name='ref_version_supersede_states_its_reason'),
        ),
        migrations.AddConstraint(
            model_name='referencedataversion',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes__isnull', False), ('supersede_reason', ''), _connector='OR'), name='ref_version_reason_only_when_superseding'),
        ),
    ]
