# Generated by Django 5.2.17 on 2026-09-18 03:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0015_reference_version_supersede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionAgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, help_text='Exclusive. NULL means currently in force.', null=True)),
                ('source_reference', models.CharField(help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.", max_length=200)),
                ('source_url', models.URLField(blank=True, help_text='Optional. Not every gazette is online, and a fabricated link is worse than none.', max_length=400)),
                ('notes', models.TextField(blank=True, help_text='Interpretation notes — how the figure was read, and anything ambiguous about it.')),
                ('is_limited', models.BooleanField(help_text="Does the instrument limit adoption leave by the child's age? No default.")),
                ('max_child_age_years', models.SmallIntegerField(blank=True, help_text='The limit, when limited. NULL when not.', null=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adoption_age_limit',
                'ordering': ['-effective_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='adoption_age_limit_effective_range_ordered'), models.CheckConstraint(condition=models.Q(('source_reference', ''), _negated=True), name='adoption_age_limit_source_reference_not_blank'), models.CheckConstraint(condition=models.Q(('is_limited', False), ('max_child_age_years__isnull', False), _connector='OR'), name='adoption_limit_states_its_age'), models.CheckConstraint(condition=models.Q(('is_limited', True), ('max_child_age_years__isnull', True), _connector='OR'), name='adoption_unlimited_states_no_age')],
            },
        ),
        migrations.CreateModel(
            name='ParentalLeaveQuantum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, help_text='Exclusive. NULL means currently in force.', null=True)),
                ('source_reference', models.CharField(help_text="Where this figure comes from, precisely enough to find it again. e.g. 'GN 7083, GG 54075, 2 Feb 2026' or 'BCCCI Collective Agreement 2026, cl 8'.", max_length=200)),
                ('source_url', models.URLField(blank=True, help_text='Optional. Not every gazette is online, and a fabricated link is worse than none.', max_length=400)),
                ('notes', models.TextField(blank=True, help_text='Interpretation notes — how the figure was read, and anything ambiguous about it.')),
                ('sole_parent_months', models.SmallIntegerField(help_text='Read-in s25(1): a single parent, or the only employed party.')),
                ('sole_parent_days', models.SmallIntegerField(help_text='Days on top of the months, if the instrument gives any. Usually zero.')),
                ('both_employed_months', models.SmallIntegerField(help_text='Read-in s25(4A): the AGGREGATE where both parties are employed.')),
                ('both_employed_days', models.SmallIntegerField(help_text='Read-in s25(4A): plus ten days.')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parental_leave_quantum',
                'ordering': ['-effective_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='parental_leave_quantum_effective_range_ordered'), models.CheckConstraint(condition=models.Q(('source_reference', ''), _negated=True), name='parental_leave_quantum_source_reference_not_blank'), models.CheckConstraint(condition=models.Q(('sole_parent_days__gte', 0), ('sole_parent_months__gte', 0), ('both_employed_days__gte', 0), ('both_employed_months__gte', 0)), name='parental_quantum_figures_not_negative')],
            },
        ),
    ]
