# Generated by Django 5.2.17 on 2026-09-19 16:25

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.functions.comparison
import statutory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0017_night_allowance_pair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statutoryparameter',
            name='uniq_statutory_parameter_per_date',
        ),
        migrations.RemoveConstraint(
            model_name='statutoryparameter',
            name='statutory_parameter_no_overlapping_periods',
        ),
        migrations.AddField(
            model_name='statutoryparameter',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='NULL means the figure applies wherever nothing more specific does.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statutory_parameters', to='statutory.sector'),
        ),
        migrations.AddField(
            model_name='statutoryparameter',
            name='sector_area',
            field=models.ForeignKey(blank=True, help_text='NULL means every area of the sector.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statutory_parameters', to='statutory.sectorarea'),
        ),
        migrations.AddConstraint(
            model_name='statutoryparameter',
            constraint=models.UniqueConstraint(fields=('parameter_code', 'sector', 'sector_area', 'effective_from'), name='uniq_statutory_parameter_per_date', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='statutoryparameter',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(statutory.models.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('parameter_code', '='), (django.db.models.functions.comparison.Coalesce('sector', models.Value(0)), '='), (django.db.models.functions.comparison.Coalesce('sector_area', models.Value(0)), '=')], name='statutory_parameter_no_overlapping_periods'),
        ),
    ]
