# Generated by Django 5.2.17 on 2026-09-19 16:44

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.functions.comparison
import statutory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0018_statutory_parameter_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaveruleset',
            name='leave_rule_set_no_overlapping_periods',
        ),
        migrations.RemoveConstraint(
            model_name='terminationruleset',
            name='termination_rule_set_no_overlapping_periods',
        ),
        migrations.RemoveConstraint(
            model_name='workingtimeruleset',
            name='working_time_rule_set_no_overlapping_periods',
        ),
        migrations.AddField(
            model_name='leaveruleset',
            name='sector_area',
            field=models.ForeignKey(blank=True, help_text='NULL means every area of the sector. Set where one area has its own instrument.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_rule_sets', to='statutory.sectorarea'),
        ),
        migrations.AddField(
            model_name='terminationruleset',
            name='sector_area',
            field=models.ForeignKey(blank=True, help_text='NULL means every area of the sector. Set where one area has its own instrument.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_rule_sets', to='statutory.sectorarea'),
        ),
        migrations.AddField(
            model_name='workingtimeruleset',
            name='sector_area',
            field=models.ForeignKey(blank=True, help_text='NULL means every area of the sector. Set where one area has its own instrument.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_rule_sets', to='statutory.sectorarea'),
        ),
        migrations.AddConstraint(
            model_name='leaveruleset',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(statutory.models.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), (django.db.models.functions.comparison.Coalesce('sector', models.Value(0)), '='), (django.db.models.functions.comparison.Coalesce('sector_area', models.Value(0)), '=')], name='leave_rule_set_no_overlapping_periods'),
        ),
        migrations.AddConstraint(
            model_name='terminationruleset',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(statutory.models.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), (django.db.models.functions.comparison.Coalesce('sector', models.Value(0)), '='), (django.db.models.functions.comparison.Coalesce('sector_area', models.Value(0)), '=')], name='termination_rule_set_no_overlapping_periods'),
        ),
        migrations.AddConstraint(
            model_name='workingtimeruleset',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(statutory.models.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), (django.db.models.functions.comparison.Coalesce('sector', models.Value(0)), '='), (django.db.models.functions.comparison.Coalesce('sector_area', models.Value(0)), '=')], name='working_time_rule_set_no_overlapping_periods'),
        ),
    ]
