# Generated by Django 5.2.17 on 2026-09-19 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0019_rule_set_area_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terminationnoticeband',
            name='contested_reason',
            field=models.TextField(blank=True, help_text='Both limbs, quoted, so the refusal names the contradiction.'),
        ),
        migrations.AddField(
            model_name='terminationnoticeband',
            name='is_contested',
            field=models.BooleanField(default=False, help_text='The instrument gives two irreconcilable answers for this band, so resolve.notice_band() REFUSES rather than preferring one.'),
        ),
        migrations.AlterField(
            model_name='terminationnoticeband',
            name='notice_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks')], max_length=10),
        ),
        migrations.AlterField(
            model_name='terminationnoticeband',
            name='notice_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The period. NULL only where the band is contested.', max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='terminationnoticeband',
            constraint=models.CheckConstraint(condition=models.Q(('is_contested', True), ('notice_value__isnull', False), _connector='OR'), name='notice_band_states_a_period_unless_contested'),
        ),
        migrations.AddConstraint(
            model_name='terminationnoticeband',
            constraint=models.CheckConstraint(condition=models.Q(('is_contested', False), models.Q(('notice_value__isnull', True), models.Q(('contested_reason', ''), _negated=True)), _connector='OR'), name='notice_band_contested_has_no_value_and_a_reason'),
        ),
    ]
