# Generated by Django 5.2.17 on 2026-09-19 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0020_notice_band_contested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='terminationnoticeband',
            name='termination_notice_band_notice_unit_is_known',
        ),
        migrations.AddConstraint(
            model_name='terminationnoticeband',
            constraint=models.CheckConstraint(condition=models.Q(('notice_unit__in', ['days', 'weeks']), models.Q(('is_contested', True), ('notice_unit', '')), _connector='OR'), name='termination_notice_band_notice_unit_is_known'),
        ),
    ]
