"""The verification tick becomes evidence in the database (D-256).

Append-only, and TenantOptionalModel's policy: no tenant may see these rows,
and a session with no tenant pinned - every management command - reads and
writes exactly them.
"""

# Generated by Django 5.2.17 on 2026-09-19 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.db.rls import append_only, disable_rls, drop_append_only, enable_rls_optional


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("statutory", "0022_long_service_annual_leave"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceFigureCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("row_key", models.CharField(db_index=True, max_length=200)),
                ("version_label", models.CharField(db_index=True, max_length=60)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("checked", "Checked against the source and correct"),
                            ("queried", "Something is wrong — see the note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value_at_check", models.CharField(max_length=400)),
                ("checked_on", models.DateField(help_text="The date the person did the checking.")),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Mandatory on a QUERY, which is the point of one."
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_figure_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "reference_figure_check",
                "indexes": [
                    models.Index(
                        fields=["row_key", "-recorded_at"], name="reference_f_row_key_6f3ad2_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("outcome__in", ["checked", "queried"])),
                        name="reference_figure_check_outcome_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("outcome", "queried"), _negated=True),
                            models.Q(("note", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="reference_figure_check_a_query_says_what_is_wrong",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("row_key", ""), _negated=True),
                        name="reference_figure_check_names_a_figure",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            enable_rls_optional("reference_figure_check"),
            disable_rls("reference_figure_check"),
        ),
        migrations.RunSQL(
            append_only("reference_figure_check"),
            drop_append_only("reference_figure_check"),
        ),
    ]
