# Generated by Django 5.2.17 on 2026-09-20 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0023_reference_figure_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedataversion',
            name='verified_by_users',
            field=models.ManyToManyField(blank=True, help_text='Everyone who checked a figure in this version. The per-figure record of who checked what is reference_figure_check.', related_name='verified_reference_versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
