# Generated by Django 5.2.17 on 2026-09-21 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0024_referencedataversion_verified_by_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terminationnoticeband',
            name='probation_condition',
            field=models.CharField(choices=[('any', 'Applies whether or not the employee is on probation'), ('on_probation', 'Only while the employee is on probation'), ('off_probation', 'Only once probation has ended')], default='any', help_text='Which employees this band is about. Most instruments say nothing.', max_length=20),
        ),
        migrations.AlterField(
            model_name='terminationnoticeband',
            name='sequence',
            field=models.PositiveSmallIntegerField(help_text="1..n, this band's identity within its rule set. NOT service order — two bands may cover one range in different probation lanes."),
        ),
        migrations.AddConstraint(
            model_name='terminationnoticeband',
            constraint=models.CheckConstraint(condition=models.Q(('probation_condition__in', ['any', 'on_probation', 'off_probation'])), name='termination_notice_band_probation_condition_is_known'),
        ),
    ]
