# Generated by Django 5.2.17 on 2026-09-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0025_terminationnoticeband_probation_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedataversion',
            name='applies_until',
            field=models.DateField(blank=True, db_index=True, help_text="Derived: the day this version's last row stops. NULL = open-ended.", null=True),
        ),
    ]
