# Generated by Django 5.2.17 on 2026-09-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statutory', '0026_referencedataversion_applies_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminationnoticeband',
            name='superseded_by_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_notice_bands', to='statutory.referencedataversion'),
        ),
    ]
