# Generated by Django 5.2.17 on 2026-09-14 09:54

import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import (
    DROP_SYSTEM_ROW_LOCK_FUNCTION,
    SYSTEM_ROW_LOCK_FUNCTION,
    disable_rls,
    drop_lock_system_rows,
    enable_rls,
    enable_rls_shared,
    lock_system_rows,
)


class Migration(migrations.Migration):
    """P4 chunk 6: ``document_category`` and ``document`` (D-138, D-139, D-140).

    ``document_category`` is the THIRD shared table — ``enable_rls_shared`` plus
    the system-row lock, same shape as ``payroll_component`` and ``leave_type``.
    Unlike ``leave_type``, ``is_system`` ships in THIS migration rather than
    being retrofitted: the column exists before ``lock_system_rows()`` is
    installed, so D-134's bug — a trigger keyed on a column that is not there
    yet, failing every UPDATE and DELETE on the table — has no window to occur.

    ``document`` is an ordinary ``TenantScopedModel`` table and takes the plain
    ``enable_rls``. Its exclusive arc and its paired verified columns are both
    plain CHECK constraints, needing no extension beyond ``btree_gist`` (already
    installed by ``statutory/0002``) — there is no EXCLUDE here, because two
    documents about the same thing coexisting is normal and a renewal chain is
    the model for it, not an overlap the schema should forbid.
    """

    initial = True

    dependencies = [
        ("core", "0005_tenantmembership_ui_preferences"),
        ("employees", "0007_recurring_component_and_entitlement_deviations"),
        ("employers", "0004_payroll_component"),
        ("statutory", "0010_alter_sectorarea_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=120)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("employer", "Employer"),
                            ("employee", "Employee"),
                            ("workplace", "Workplace"),
                            ("any", "Any"),
                        ],
                        default="employee",
                        help_text="What a document in this category may attach to. 'any' fits all four.",
                        max_length=20,
                    ),
                ),
                (
                    "requires_expiry_date",
                    models.BooleanField(
                        default=False,
                        help_text="Work permits, police clearances, COIDA letters of good standing.",
                    ),
                ),
                (
                    "is_required_for_onboarding",
                    models.BooleanField(
                        default=False,
                        help_text="Feeds the outstanding-documents count on the employee file.",
                    ),
                ),
                (
                    "visible_to_employee",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "WHITELIST, default deny. TRUE only for the employment contract. A "
                            "category added later is invisible until someone deliberately opens it."
                        ),
                    ),
                ),
                (
                    "is_confidential_by_default",
                    models.BooleanField(
                        default=False,
                        help_text="Hides from the read_only role. Separate question from D-44's whitelist.",
                    ),
                ),
                (
                    "default_retention_months",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Seeds file_object.retention_until on upload.",
                        null=True,
                    ),
                ),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System categories cannot be edited or deleted (D-93).",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "NULL fits every sector. Set only where the category is meaningless "
                            "outside one — CIPC and BEE are not household documents."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_categories",
                        to="statutory.sector",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_category",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attached_to",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("employer", "Employer"),
                            ("employee", "Employee"),
                            ("workplace", "Workplace"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Permit number, CIPC registration number, certificate number.",
                        max_length=60,
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, help_text="Date on the document itself.", null=True
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Drives alerts at 60, 30 and 7 days (P9).", null=True
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False,
                        help_text="Defaulted from the category; hides from the read_only role.",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only when attached_to='employee'.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="employees.employee",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Set when attached_to='employer', and also when 'employee' or "
                            "'workplace' name one."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="employers.employer",
                    ),
                ),
                (
                    "file_object",
                    models.ForeignKey(
                        help_text="Carries the virus scan status, checksum and retention date.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.fileobject",
                    ),
                ),
                (
                    "supersedes_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="A renewed permit supersedes rather than replaces the old one.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="documents.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Someone confirmed this is what it claims to be.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Set only when attached_to='workplace' — client contracts, site "
                            "instructions, safety files."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="employers.workplace",
                    ),
                ),
                (
                    "document_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="documents.documentcategory",
                    ),
                ),
            ],
            options={
                "db_table": "document",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="documentcategory",
            index=models.Index(
                fields=["applies_to", "is_active"], name="document_ca_applies_321bb3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentcategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.comparison.Coalesce("tenant_id", models.Value(0)),
                models.F("code"),
                name="uniq_document_category_code_per_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("applies_to__in", ["tenant", "employer", "employee", "workplace", "any"])
                ),
                name="document_category_applies_to_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tenant__isnull", False), ("is_system", True), _connector="OR"
                ),
                name="document_category_shared_rows_are_system_rows",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tenant__isnull", True), ("is_system", False), _connector="OR"
                ),
                name="document_category_system_rows_are_shared_rows",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["tenant", "attached_to"], name="document_tenant__809b69_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("employee__isnull", False)),
                fields=["employee", "document_category"],
                name="document_employee_category_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("employer__isnull", False)),
                fields=["employer"],
                name="document_employer_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("workplace__isnull", False)),
                fields=["workplace"],
                name="document_workplace_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("expiry_date__isnull", False)),
                fields=["tenant", "expiry_date"],
                name="document_tenant_expiry_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("attached_to__in", ["tenant", "employer", "employee", "workplace"])),
                name="document_attached_to_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("attached_to", "tenant"),
                        ("employee__isnull", True),
                        ("employer__isnull", True),
                        ("workplace__isnull", True),
                    ),
                    models.Q(
                        ("attached_to", "employer"),
                        ("employee__isnull", True),
                        ("employer__isnull", False),
                        ("workplace__isnull", True),
                    ),
                    models.Q(
                        ("attached_to", "employee"),
                        ("employee__isnull", False),
                        ("workplace__isnull", True),
                    ),
                    models.Q(
                        ("attached_to", "workplace"),
                        ("employee__isnull", True),
                        ("workplace__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="document_exclusive_arc",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("verified_at__isnull", True), ("verified_by_user__isnull", True)),
                    models.Q(("verified_at__isnull", False), ("verified_by_user__isnull", False)),
                    _connector="OR",
                ),
                name="document_verified_by_and_at_together",
            ),
        ),
        migrations.RunSQL(SYSTEM_ROW_LOCK_FUNCTION, DROP_SYSTEM_ROW_LOCK_FUNCTION),
        migrations.RunSQL(
            enable_rls_shared("document_category"), disable_rls("document_category")
        ),
        migrations.RunSQL(
            lock_system_rows("document_category"), drop_lock_system_rows("document_category")
        ),
        migrations.RunSQL(enable_rls("document"), disable_rls("document")),
    ]
