# Generated by Django 5.2.17 on 2026-09-13 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """Pay periods, generated from a pay group's calendar and never typed.

    Tenant-scoped, so ``enable_rls`` below.

    The constraints are the workbook's, including ``payment_date >= period_start``
    rather than ``>= period_end``: a period may legitimately pay before it ends, which
    is what a salaried month paid on the 25th does.
    """


    initial = True

    dependencies = [
        ("core", "0004_audit_read_operation"),
        ("employers", "0003_paygroup"),
        ("statutory", "0008_reference_tables_refuse_deletes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_number",
                    models.SmallIntegerField(
                        help_text="1..12 monthly, 1..52 weekly, within the tax year."
                    ),
                ),
                ("period_start", models.DateField(db_index=True)),
                ("period_end", models.DateField(db_index=True)),
                (
                    "payment_date",
                    models.DateField(
                        db_index=True,
                        help_text="Determines which tax year the earnings fall into.",
                    ),
                ),
                (
                    "working_days_in_period",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Days in the period matching the employer's working pattern. Public holidays are NOT subtracted: one falling on an ordinary working day is paid, so it is an available day for pay purposes.",
                        max_digits=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reopened_count",
                    models.SmallIntegerField(
                        default=0, help_text="Every reopen is an audited event."
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_periods",
                        to="employers.paygroup",
                    ),
                ),
                (
                    "tax_year",
                    models.ForeignKey(
                        help_text="The year the PAYMENT DATE falls into, not the period end.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_periods",
                        to="statutory.taxyear",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_period",
                "ordering": ["pay_group_id", "period_start"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="pay_period_tenant__78e8db_idx",
                    ),
                    models.Index(
                        fields=["payment_date"], name="pay_period_payment_8551bb_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pay_group", "period_start"),
                        name="uniq_period_start_per_pay_group",
                    ),
                    models.UniqueConstraint(
                        fields=("pay_group", "tax_year", "period_number"),
                        name="uniq_period_number_per_group_year",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_end__gte", models.F("period_start"))
                        ),
                        name="pay_period_end_not_before_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("payment_date__gte", models.F("period_start"))
                        ),
                        name="pay_period_payment_not_before_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reopened_count__gte", 0)),
                        name="pay_period_reopened_count_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("closed_at__isnull", False), ("status", "closed")
                            ),
                            models.Q(("status", "closed"), _negated=True),
                            _connector="OR",
                        ),
                        name="pay_period_closed_has_a_timestamp",
                    ),
                ],
            },
        ),
            migrations.RunSQL(enable_rls("pay_period"), disable_rls("pay_period")),
    ]
