"""payroll_calculation_trace - invariant 5 (D-208).

Tenant-scoped, so ``enable_rls`` below and the generated isolation suite picks it
up the day it is written. And append-only by TRIGGER, like a ledger row: a trace
that can be edited after the fact is not evidence of anything.
"""

# Generated by Django 5.2.17 on 2026-09-19 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import append_only, disable_rls, drop_append_only, enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0012_statutory_method_covers_parental'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCalculationTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payslip_id_ref', models.BigIntegerField(blank=True, db_index=True, help_text="Becomes a real FK to payslip when P7's assembly is built.", null=True)),
                ('calculator', models.CharField(db_index=True, help_text="e.g. 'uif.contribution'.", max_length=60)),
                ('calculated_for', models.DateField(db_index=True, help_text='The date the calculation is FOR, never the date it ran.')),
                ('inputs', models.JSONField(help_text='Every input, as given. Strings, so it reads the same in 2029.')),
                ('statutory_rows', models.JSONField(default=list, help_text='[["table", row_id], ...] - keys, never citation text.')),
                ('outputs', models.JSONField(help_text='Every figure produced, unrounded.')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_traces', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_calculation_trace',
                'ordering': ['-calculated_for', '-id'],
                'indexes': [models.Index(fields=['tenant', 'calculator', 'calculated_for'], name='payroll_cal_tenant__0552b3_idx'), models.Index(fields=['employee', 'calculated_for'], name='payroll_cal_employe_fc1369_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('calculator', ''), _negated=True), name='calculation_trace_names_its_calculator')],
            },
        ),
            migrations.RunSQL(
            enable_rls("payroll_calculation_trace"),
            disable_rls("payroll_calculation_trace"),
        ),
        migrations.RunSQL(
            append_only("payroll_calculation_trace"),
            drop_append_only("payroll_calculation_trace"),
        ),
    ]
