# Generated by Django 5.2.17 on 2026-09-19 14:18

import django.db.models.deletion
import django.db.models.functions.math
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import (
    DROP_FINALISED_ROW_FUNCTION,
    FINALISED_ROW_FUNCTION,
    disable_rls,
    drop_no_change_when_finalised,
    enable_rls,
    no_change_when_finalised,
)

#: Every one of these holds employer and employee data, so every one gets the
#: full FORCE RLS policy. leave/0003 shipped three tables without it and only
#: the generated isolation suite noticed (D-169); payroll/0002 repeated it a
#: chunk later (D-208). Written into the migration by hand because
#: makemigrations does not know about any of this.
NEW_TABLES = ["payroll_run", "payslip", "payslip_line", "ytd_accumulator"]


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0012_statutory_method_covers_parental'),
        ('employers', '0004_payroll_component'),
        ('payroll', '0002_payroll_calculation_trace'),
        ('statutory', '0017_night_allowance_pair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollcalculationtrace',
            name='payslip_id_ref',
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_number', models.SmallIntegerField(default=1, help_text='1 for the ordinary run; 2+ for a correction run over the same period.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculating', 'Calculating'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('finalised', 'Finalised'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finalised_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalised_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.payperiod')),
                ('reverses_run', models.OneToOneField(blank=True, help_text='Set on a reversal run, naming the run it undoes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='payroll.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_run',
                'ordering': ['pay_period_id', 'run_number'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_snapshot', models.JSONField(blank=True, default=dict, help_text='Name, number, position, rate and bank reference as at finalisation.')),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employer_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_finalised', models.BooleanField(db_index=True, default=False)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('is_reversal', models.BooleanField(default=False, help_text='A reversing payslip. Its lines are the negation of the original.')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollrun')),
                ('reverses_payslip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='payroll.payslip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payslip',
                'ordering': ['payroll_run_id', 'employee_id'],
            },
        ),
        migrations.AddField(
            model_name='payrollcalculationtrace',
            name='payslip',
            field=models.ForeignKey(blank=True, help_text='Null while a calculation is run outside a payslip, as every test does.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_traces', to='payroll.payslip'),
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_code', models.CharField(max_length=40)),
                ('source_code', models.CharField(blank=True, help_text='The SARS code as it stood, for the IRP5.', max_length=10)),
                ('description', models.CharField(max_length=160)),
                ('sequence', models.SmallIntegerField(default=0, help_text='Display order on the document.')),
                ('units', models.DecimalField(decimal_places=4, default=0, help_text='Hours, days or periods.', max_digits=12)),
                ('rate', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('amount_exact', models.DecimalField(decimal_places=6, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payroll_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='employers.payrollcomponent')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payslip_line',
                'ordering': ['payslip_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='YtdAccumulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_code', models.CharField(db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('units', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('payslip_count', models.IntegerField(default=0)),
                ('rebuilt_at', models.DateTimeField(help_text='When this row was last recomputed from finalised payslips.')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ytd_accumulators', to='employees.employee')),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ytd_accumulators', to='statutory.taxyear')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ytd_accumulator',
                'ordering': ['employee_id', 'tax_year_id', 'source_code'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['tenant', 'status'], name='payroll_run_tenant__8d5d7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('pay_period', 'run_number'), name='uniq_run_number_per_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('run_number__gte', 1)), name='payroll_run_number_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='payroll_run_approved_has_a_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'finalised'), _negated=True), ('finalised_at__isnull', False), _connector='OR'), name='payroll_run_finalised_has_a_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('finalised_at__isnull', True), ('finalised_by_user__isnull', False), _connector='OR'), name='payroll_run_finalised_names_who'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant', 'is_finalised'], name='payslip_tenant__a75a51_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', '-finalised_at'], name='payslip_employe_a73122_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='uniq_payslip_per_employee_per_run'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finalised_at__isnull', True), ('is_finalised', False)), models.Q(('finalised_at__isnull', False), ('is_finalised', True)), _connector='OR'), name='payslip_finalised_has_a_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(('is_reversal', True), ('reverses_payslip__isnull', True), _connector='OR'), name='payslip_only_a_reversal_reverses_something'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(('is_reversal', False), ('reverses_payslip__isnull', False), _connector='OR'), name='payslip_a_reversal_names_what_it_reverses'),
        ),
        migrations.AddIndex(
            model_name='payslipline',
            index=models.Index(fields=['tenant', 'component_code'], name='payslip_lin_tenant__73a15a_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipline',
            index=models.Index(fields=['payslip', 'sequence'], name='payslip_lin_payslip_0bed1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('component_code', ''), _negated=True), name='payslip_line_names_its_component'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.functions.math.Round(models.F('amount_exact'), 2))), name='payslip_line_amount_is_the_exact_figure_rounded'),
        ),
        migrations.AddIndex(
            model_name='ytdaccumulator',
            index=models.Index(fields=['tenant', 'tax_year'], name='ytd_accumul_tenant__1e5623_idx'),
        ),
        migrations.AddConstraint(
            model_name='ytdaccumulator',
            constraint=models.UniqueConstraint(fields=('employee', 'tax_year', 'source_code'), name='uniq_ytd_per_employee_year_code'),
        ),
        migrations.AddConstraint(
            model_name='ytdaccumulator',
            constraint=models.CheckConstraint(condition=models.Q(('payslip_count__gte', 0)), name='ytd_payslip_count_not_negative'),
        ),
    ]

    operations += [
        migrations.RunSQL(enable_rls(table), reverse_sql=disable_rls(table))
        for table in NEW_TABLES
    ]

    # Invariant 4, by trigger rather than by convention: a REVOKE does not bind
    # the table owner and the application connects as the owner.
    operations += [
        migrations.RunSQL(FINALISED_ROW_FUNCTION, reverse_sql=DROP_FINALISED_ROW_FUNCTION),
        migrations.RunSQL(
            no_change_when_finalised("payslip"),
            reverse_sql=drop_no_change_when_finalised("payslip"),
        ),
    ]
