# Generated by Django 5.2.17 on 2026-09-19 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0012_statutory_method_covers_parental'),
        ('payroll', '0003_payslip_and_ytd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text="A stable identifier, e.g. 'reference_data'.", max_length=60)),
                ('severity', models.CharField(choices=[('blocking', 'Blocking'), ('warning', 'Warning')], db_index=True, max_length=20)),
                ('message', models.TextField(help_text='What is wrong, in the terms the employer must act on.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Null for an issue about the run or the period rather than a person.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_validation_issues', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='payroll.payrollrun')),
                ('resolved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_payroll_issues', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_validation_issue',
                'ordering': ['payroll_run_id', 'severity', 'employee_id', 'code'],
                'indexes': [models.Index(fields=['tenant', 'severity'], name='payroll_val_tenant__0f7ba9_idx'), models.Index(fields=['payroll_run', 'resolved_at'], name='payroll_val_payroll_031f52_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='validation_issue_has_a_code'), models.CheckConstraint(condition=models.Q(('message', ''), _negated=True), name='validation_issue_says_what_is_wrong'), models.CheckConstraint(condition=models.Q(models.Q(('resolution_reason', ''), ('resolved_at__isnull', True), ('resolved_by_user__isnull', True)), models.Q(('resolved_at__isnull', False), ('resolved_by_user__isnull', False), models.Q(('resolution_reason', ''), _negated=True)), _connector='OR'), name='validation_issue_resolution_is_named_and_reasoned')],
            },
        ),
    ]

    # Employer and employee data, so the full FORCE RLS policy. makemigrations
    # produces none of this; leave/0003 and payroll/0002 both shipped short.
    operations += [
        migrations.RunSQL(
            enable_rls("payroll_validation_issue"),
            reverse_sql=disable_rls("payroll_validation_issue"),
        )
    ]
