# Generated by Django 5.2.17 on 2026-09-24 08:39

import django.db.models.deletion
import django.db.models.functions.math
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0013_employeeunionrole'),
        ('payroll', '0004_payroll_validation_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBonusCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_start', models.DateField(db_index=True)),
                ('cycle_end', models.DateField()),
                ('bonus_weeks', models.DecimalField(decimal_places=3, help_text='From termination_rule_set, as in force.', max_digits=6)),
                ('full_months_worked', models.SmallIntegerField(default=0)),
                ('accrued_amount_exact', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('accrued_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accrued_as_at', models.DateField(help_text='The date full_months_worked and the accrued amount were computed as at.')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('accruing', 'Accruing'), ('paid', 'Paid'), ('pro_rata_paid', 'Pro rata paid on termination'), ('forfeited', 'Forfeited')], db_index=True, default='accruing', max_length=20)),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_bonus_cycles', to='employees.employee')),
                ('paid_in_payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_bonus_cycles_paid', to='payroll.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
                ('updated_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annual_bonus_cycle',
                'ordering': ['employee_id', 'cycle_start'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='annual_bonu_tenant__7f9338_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'cycle_start'), name='uniq_bonus_cycle_per_employee_start'), models.CheckConstraint(condition=models.Q(('status__in', ['accruing', 'paid', 'pro_rata_paid', 'forfeited'])), name='bonus_cycle_status_is_known'), models.CheckConstraint(condition=models.Q(('cycle_end__gte', models.F('cycle_start'))), name='bonus_cycle_ends_after_it_starts'), models.CheckConstraint(condition=models.Q(('full_months_worked__gte', 0), ('full_months_worked__lte', 12)), name='bonus_cycle_months_within_a_year'), models.CheckConstraint(condition=models.Q(('accrued_amount', django.db.models.functions.math.Round(models.F('accrued_amount_exact'), 2))), name='bonus_cycle_amount_is_the_exact_amount_rounded'), models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='bonus_cycle_paid_not_negative'), models.CheckConstraint(condition=models.Q(models.Q(('paid_in_payroll_run__isnull', True), ('status__in', ['accruing', 'forfeited'])), models.Q(('paid_in_payroll_run__isnull', False), ('status__in', ['paid', 'pro_rata_paid'])), _connector='OR'), name='bonus_cycle_a_payment_names_its_run')],
            },
        ),
    ]

    # Employee data, so the full FORCE RLS policy. makemigrations produces none
    # of this; leave/0003 and payroll/0002 both shipped short (D-169).
    operations += [
        migrations.RunSQL(
            enable_rls("annual_bonus_cycle"),
            reverse_sql=disable_rls("annual_bonus_cycle"),
        )
    ]
