# Generated by Django 5.2.17 on 2026-09-24 15:25

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math
from django.conf import settings
from django.db import migrations, models


TOTAL_COLUMNS = (
    "employee_count",
    "total_gross",
    "total_paye",
    "total_uif_employee",
    "total_uif_employer",
    "total_sdl",
    "total_other_deductions",
    "total_net_pay",
    "total_employer_cost",
)

TOTALS_LOCK = f"""
CREATE OR REPLACE FUNCTION labourmax_payroll_run_totals_locked() RETURNS trigger AS $$
BEGIN
    IF OLD.status IN ('finalised', 'reversed') AND (
        {" OR ".join(f"NEW.{c} IS DISTINCT FROM OLD.{c}" for c in TOTAL_COLUMNS)}
    ) THEN
        RAISE EXCEPTION 'The totals of a finalised payroll run cannot change. A correction is a reversal run plus a replacement (invariant 4).';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS payroll_run_totals_locked ON payroll_run;
CREATE TRIGGER payroll_run_totals_locked BEFORE UPDATE ON payroll_run
    FOR EACH ROW EXECUTE FUNCTION labourmax_payroll_run_totals_locked();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileobject_content_purged_at'),
        ('employees', '0013_employeeunionrole'),
        ('employers', '0004_payroll_component'),
        ('payroll', '0005_annual_bonus_cycle'),
        ('statutory', '0026_referencedataversion_applies_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollvalidationissue',
            options={'ordering': ['payroll_run_id', 'severity', 'employee_id', 'issue_code']},
        ),
        migrations.AlterModelOptions(
            name='payslipline',
            options={'ordering': ['payslip_id', 'line_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='ytdaccumulator',
            options={'ordering': ['employee_id', 'tax_year_id']},
        ),
        migrations.RemoveConstraint(
            model_name='payrollcalculationtrace',
            name='calculation_trace_names_its_calculator',
        ),
        migrations.RemoveConstraint(
            model_name='payrollvalidationissue',
            name='validation_issue_has_a_code',
        ),
        migrations.RemoveConstraint(
            model_name='payrollvalidationissue',
            name='validation_issue_resolution_is_named_and_reasoned',
        ),
        migrations.RemoveConstraint(
            model_name='payslipline',
            name='payslip_line_amount_is_the_exact_figure_rounded',
        ),
        migrations.RemoveConstraint(
            model_name='ytdaccumulator',
            name='uniq_ytd_per_employee_year_code',
        ),
        migrations.RemoveConstraint(
            model_name='ytdaccumulator',
            name='ytd_payslip_count_not_negative',
        ),
        migrations.RemoveIndex(
            model_name='payrollcalculationtrace',
            name='payroll_cal_tenant__0552b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollvalidationissue',
            name='payroll_val_payroll_031f52_idx',
        ),
        migrations.RemoveIndex(
            model_name='payslipline',
            name='payslip_lin_payslip_0bed1a_idx',
        ),
        migrations.RenameField(
            model_name='payrollcalculationtrace',
            old_name='calculator',
            new_name='calculator_name',
        ),
        migrations.RenameField(
            model_name='payrollcalculationtrace',
            old_name='statutory_rows',
            new_name='reference_rows_used',
        ),
        migrations.RenameField(
            model_name='payrollvalidationissue',
            old_name='resolved_at',
            new_name='acknowledged_at',
        ),
        migrations.RenameField(
            model_name='payrollvalidationissue',
            old_name='code',
            new_name='issue_code',
        ),
        migrations.RenameField(
            model_name='payslip',
            old_name='gross_earnings',
            new_name='total_earnings',
        ),
        migrations.RenameField(
            model_name='payslip',
            old_name='employer_contributions',
            new_name='total_employer_contributions',
        ),
        migrations.RenameField(
            model_name='payslipline',
            old_name='sequence',
            new_name='line_order',
        ),
        # Two renames the autodetector could not offer, because each field's
        # shape changes with its name: RENAMED, never dropped and re-added.
        migrations.RenameField(
            model_name='payrollvalidationissue',
            old_name='resolved_by_user',
            new_name='acknowledged_by_user',
        ),
        migrations.RenameField(
            model_name='payslipline',
            old_name='amount_exact',
            new_name='amount_unrounded',
        ),
        migrations.RemoveField(
            model_name='ytdaccumulator',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ytdaccumulator',
            name='payslip_count',
        ),
        migrations.RemoveField(
            model_name='ytdaccumulator',
            name='rebuilt_at',
        ),
        migrations.RemoveField(
            model_name='ytdaccumulator',
            name='source_code',
        ),
        migrations.RemoveField(
            model_name='ytdaccumulator',
            name='units',
        ),
        migrations.AddField(
            model_name='payrollcalculationtrace',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollcalculationtrace',
            name='sequence',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='calculated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculated_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='employee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='employers.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='engine_version',
            field=models.CharField(default='P7.8', help_text='calculators.base.ENGINE_VERSION when calculated — needed to reproduce a run.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reference_data_version',
            field=models.ForeignKey(blank=True, help_text='The statutory data version the run was calculated against.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='statutory.referencedataversion'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='run_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('supplementary', 'Supplementary'), ('termination', 'Termination'), ('bonus', 'Bonus'), ('correction', 'Correction')], db_index=True, default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_employer_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gross + UIF employer + SDL + COIDA provision.', max_digits=16),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_sdl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_uif_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_uif_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='validation_summary',
            field=models.JSONField(blank=True, default=list, help_text='Blocking errors and non-blocking warnings.'),
        ),
        migrations.AlterField(
            model_name='payrollvalidationissue',
            name='acknowledged_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_payroll_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollvalidationissue',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payslip',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employeebankaccount'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='days_worked',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='payslip',
            name='engagement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employeeengagement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='gross_remuneration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='is_termination_payslip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payslip',
            name='ordinary_hours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pay_basis',
            field=models.CharField(default='monthly', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='pay_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payperiod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_method',
            field=models.CharField(choices=[('eft', 'EFT'), ('cash', 'Cash')], default='eft', max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payslip_number',
            field=models.CharField(default='LEGACY', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='rate_used',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='sdl_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='sdl_remuneration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='taxable_remuneration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='uif_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='uif_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='uif_remuneration',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base after the ceiling is applied.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='amount_unrounded',
            field=models.DecimalField(decimal_places=6, help_text='Retained so rounding can be reconciled.', max_digits=18),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='calculation_note',
            field=models.CharField(blank=True, help_text='Plain-English explanation for the drill-down.', max_length=255),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='component_type',
            field=models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer contribution'), ('informational', 'Informational')], db_index=True, default='earning', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipline',
            name='is_sdl_base',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='is_uif_base',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='sars_source_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='statutory.sarssourcecode'),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days'), ('months', 'Months'), ('none', 'None')], max_length=10),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ytd_accumulators', to='employers.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='last_payroll_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ytd_accumulators', to='payroll.payrollrun'),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='periods_processed',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='recalculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='ytd_by_source_code',
            field=models.JSONField(blank=True, default=dict, help_text="{'3601': '45000.00', ...} — the IRP5 payload."),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='ytd_coida_remuneration',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Capped at the COIDA ceiling.', max_digits=16),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='ytd_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='ytd_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='ytd_sdl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='ytd_taxable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='ytd_uif_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='ytd_uif_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ytdaccumulator',
            name='ytd_uif_remuneration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('calculating', 'Calculating'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('finalised', 'Finalised'), ('reversed', 'Reversed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollvalidationissue',
            name='severity',
            field=models.CharField(choices=[('error', 'Error — blocks approval'), ('warning', 'Warning'), ('info', 'Information')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Rounded HALF_UP to 2dp at this level only.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Hours or days.', max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='payrollcalculationtrace',
            index=models.Index(fields=['tenant', 'calculator_name', 'calculated_for'], name='payroll_cal_tenant__6a0357_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcalculationtrace',
            index=models.Index(fields=['payslip', 'sequence'], name='payroll_cal_payslip_94487c_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['employer', '-finalised_at'], name='payroll_run_employe_486e72_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollvalidationissue',
            index=models.Index(fields=['payroll_run', 'acknowledged_at'], name='payroll_val_payroll_e88661_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'pay_period'], name='payslip_employe_525a81_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant', 'pay_period'], name='payslip_tenant__0e3f19_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipline',
            index=models.Index(fields=['payslip', 'line_order'], name='payslip_lin_payslip_d7e3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipline',
            index=models.Index(fields=['tenant', 'payroll_component'], name='payslip_lin_tenant__4b0dc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollcalculationtrace',
            constraint=models.CheckConstraint(condition=models.Q(('calculator_name', ''), _negated=True), name='calculation_trace_names_its_calculator'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'calculating', 'calculated', 'approved', 'finalised', 'reversed', 'failed'])), name='payroll_run_status_is_known'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('run_type__in', ['regular', 'supplementary', 'termination', 'bonus', 'correction'])), name='payroll_run_type_is_known'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('engine_version', ''), _negated=True), name='payroll_run_names_its_engine_version'),
        ),
        migrations.AddConstraint(
            model_name='payrollvalidationissue',
            constraint=models.CheckConstraint(condition=models.Q(('issue_code', ''), _negated=True), name='validation_issue_has_a_code'),
        ),
        migrations.AddConstraint(
            model_name='payrollvalidationissue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('acknowledged_at__isnull', True), ('acknowledged_by_user__isnull', True), ('resolution_reason', '')), models.Q(('acknowledged_at__isnull', False), ('acknowledged_by_user__isnull', False), models.Q(('resolution_reason', ''), _negated=True)), _connector='OR'), name='validation_issue_resolution_is_named_and_reasoned'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('tenant', 'payslip_number'), name='uniq_payslip_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(('payslip_number', ''), _negated=True), name='payslip_has_a_number'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(('net_pay', django.db.models.expressions.CombinedExpression(models.F('total_earnings'), '-', models.F('total_deductions')))), name='payslip_net_is_earnings_less_deductions'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(('is_reversal', True), ('net_pay__gte', 0), _connector='OR'), name='payslip_net_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['eft', 'cash'])), name='payslip_payment_method_is_known'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.functions.math.Round(models.F('amount_unrounded'), 2))), name='payslip_line_amount_is_the_exact_figure_rounded'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('component_type__in', ['earning', 'deduction', 'employer_contribution', 'informational'])), name='payslip_line_component_type_is_known'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_type__in', ['', 'hours', 'days', 'months', 'none'])), name='payslip_line_unit_type_is_known'),
        ),
        migrations.AddConstraint(
            model_name='ytdaccumulator',
            constraint=models.UniqueConstraint(fields=('employee', 'tax_year', 'employer'), name='uniq_ytd_per_employee_year_employer'),
        ),
        migrations.AddConstraint(
            model_name='ytdaccumulator',
            constraint=models.CheckConstraint(condition=models.Q(('periods_processed__gte', 0)), name='ytd_periods_processed_not_negative'),
        ),
    ]

    # Sheet 02 calls a blocking issue an "error". Stored values move with it;
    # there are no rows today, and the statement costs nothing if there are.
    operations += [
        migrations.RunSQL(
            "UPDATE payroll_validation_issue SET severity = 'error' WHERE severity = 'blocking'",
            reverse_sql=(
                "UPDATE payroll_validation_issue SET severity = 'blocking' "
                "WHERE severity = 'error'"
            ),
        ),
        # Sheet 03: "No UPDATE of totals once status='finalised'". A finalised
        # run still moves to 'reversed', so this is not a blanket refusal - it
        # refuses a change to any TOTAL, which is what the sheet names.
        migrations.RunSQL(
            TOTALS_LOCK,
            reverse_sql=(
                "DROP TRIGGER IF EXISTS payroll_run_totals_locked ON payroll_run; "
                "DROP FUNCTION IF EXISTS labourmax_payroll_run_totals_locked();"
            ),
        ),
    ]
