# Generated by Django 5.2.17 on 2026-09-24 15:57

import django.db.models.deletion
from django.db import migrations, models

from core.db.rls import append_only, drop_append_only


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_reconcile_with_sheet_02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollcalculationtrace',
            name='payslip',
            field=models.ForeignKey(blank=True, help_text='Null while a calculation is run outside a payslip, as every test does.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_traces', to='payroll.payslip'),
        ),
    ]

    # D-294. The trace was append-only outright (D-208), which made a DRAFT
    # payslip undeletable once anything had been calculated for it - and a run
    # is recalculated as often as its attendance changes. Now: UPDATE is always
    # refused; DELETE is refused unless the row belongs to a payslip that is
    # NOT finalised. A trace with no payslip (a what-if, COIDA) stays
    # append-only for ever. A payslip already deleted in this transaction was a
    # draft, since a finalised one cannot be deleted at all.
    operations += [
        migrations.RunSQL(
            drop_append_only("payroll_calculation_trace"),
            reverse_sql=append_only("payroll_calculation_trace"),
        ),
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION labourmax_trace_follows_its_payslip() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'payroll_calculation_trace is append-only: a trace is evidence and is never edited.';
    END IF;
    -- A payslip already gone was a DRAFT: a finalised payslip cannot be deleted
    -- at all (its own trigger, D-229), and Django's foreign keys are DEFERRABLE,
    -- so the collector may delete the payslip before its traces. The row is in
    -- this session's own tenant, so RLS cannot be what hides it.
    IF OLD.payslip_id IS NULL OR COALESCE(
        (SELECT is_finalised FROM payslip WHERE id = OLD.payslip_id), FALSE
    ) THEN
        RAISE EXCEPTION 'This trace is the evidence behind a finalised payslip, or behind none, and is never deleted (invariant 5).';
    END IF;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS payroll_calculation_trace_follows_payslip ON payroll_calculation_trace;
CREATE TRIGGER payroll_calculation_trace_follows_payslip
    BEFORE UPDATE OR DELETE ON payroll_calculation_trace
    FOR EACH ROW EXECUTE FUNCTION labourmax_trace_follows_its_payslip();
""",
            reverse_sql=(
                "DROP TRIGGER IF EXISTS payroll_calculation_trace_follows_payslip "
                "ON payroll_calculation_trace; "
                "DROP FUNCTION IF EXISTS labourmax_trace_follows_its_payslip();"
            ),
        ),
    ]
