# Generated by Django 5.2.17 on 2026-09-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employeeunionrole'),
        ('payroll', '0007_trace_goes_with_a_draft_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipline',
            name='recurring_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='employees.employeerecurringcomponent'),
        ),
    ]
