# Generated by Django 5.2.17 on 2026-09-24 19:54

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0014_recurring_balance_is_the_principal"),
        ("payroll", "0008_payslip_line_names_its_recurring_line"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminationPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("termination_date", models.DateField()),
                ("termination_reason_code", models.CharField(max_length=40)),
                ("completed_months_service", models.SmallIntegerField(default=0)),
                ("completed_years_service", models.SmallIntegerField(default=0)),
                (
                    "weekly_wage_used",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Basis for notice and severance.",
                        max_digits=14,
                    ),
                ),
                (
                    "daily_wage_used",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Basis for leave pay-out.",
                        max_digits=14,
                    ),
                ),
                (
                    "monthly_wage_used",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Basis for the pro-rata bonus.",
                        max_digits=14,
                    ),
                ),
                (
                    "notice_weeks_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notice_worked", models.BooleanField(default=True)),
                (
                    "notice_pay_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "accrued_leave_days",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Statutory annual leave not taken.",
                        max_digits=8,
                    ),
                ),
                (
                    "leave_payout_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("severance_applicable", models.BooleanField(default=False)),
                ("severance_weeks", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "severance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("bonus_applicable", models.BooleanField(default=False)),
                ("bonus_months_worked", models.SmallIntegerField(default=0)),
                (
                    "bonus_pro_rata_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "outstanding_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_payout_gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "severance_tax_treatment",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("directive_required", "SARS directive required"),
                        ],
                        default="standard",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("processed", "Processed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "calculation_detail",
                    models.JSONField(
                        default=dict, help_text="Full working for the certificate of service pack."
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termination_payouts",
                        to="employees.employee",
                    ),
                ),
                (
                    "engagement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termination_payout",
                        to="employees.employeeengagement",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="The run that paid it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termination_payouts",
                        to="payroll.payrollrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "termination_payout",
                "ordering": ["-termination_date", "pk"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="termination_tenant__0be7c6_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["draft", "reviewed", "processed", "cancelled"])
                        ),
                        name="termination_payout_status_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("severance_tax_treatment__in", ["standard", "directive_required"])
                        ),
                        name="termination_payout_severance_tax_treatment_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "total_payout_gross",
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            models.F("notice_pay_amount"),
                                            "+",
                                            models.F("leave_payout_amount"),
                                        ),
                                        "+",
                                        models.F("severance_amount"),
                                    ),
                                    "+",
                                    models.F("bonus_pro_rata_amount"),
                                ),
                            )
                        ),
                        name="termination_payout_total_is_its_parts",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("payroll_run__isnull", False), ("status", "processed")),
                            models.Q(
                                models.Q(("status", "processed"), _negated=True),
                                ("payroll_run__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="termination_payout_processed_names_its_run",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            enable_rls("termination_payout"),
            reverse_sql=disable_rls("termination_payout"),
        ),
    ]
