# Generated by Django 5.2.17 on 2026-09-14 12:53

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import (
    DROP_LOCKED_ROW_FUNCTION,
    LOCKED_ROW_FUNCTION,
    disable_rls,
    drop_no_update_when_locked,
    enable_rls,
    no_update_when_locked,
)


class Migration(migrations.Migration):
    """``attendance_day`` — P5 chunk 1. An ordinary ``TenantScopedModel`` table,
    plus ``no_update_when_locked()`` for invariant 4: once a payroll run
    finalises, the days it paid freeze at the database, not only in the
    application. See ``core/db/rls.py`` and the model docstring for why a
    trigger and not a REVOKE.
    """

    initial = True

    dependencies = [
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0008_employeeimportbatch_employee_created_by_import_batch_and_more"),
        ("employers", "0004_payroll_component"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_date",
                    models.DateField(help_text="Partition key candidate (yearly) at volume."),
                ),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("ordinary", "Ordinary"),
                            ("rest_day", "Rest day"),
                            ("sunday", "Sunday"),
                            ("public_holiday", "Public holiday"),
                            ("leave", "Leave"),
                            ("absent_unpaid", "Absent — unpaid"),
                            ("absent_paid", "Absent — paid"),
                            ("no_work_available", "No work available"),
                        ],
                        db_index=True,
                        default="ordinary",
                        max_length=25,
                    ),
                ),
                (
                    "leave_application_id_ref",
                    models.BigIntegerField(
                        blank=True,
                        help_text=(
                            "Becomes a real FK to leave_application in P6. Set only when "
                            "day_type='leave'."
                        ),
                        null=True,
                    ),
                ),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("unpaid_break_minutes", models.SmallIntegerField(default=0)),
                (
                    "ordinary_hours",
                    models.DecimalField(
                        decimal_places=3, default=0, help_text="Hours at 1.0x.", max_digits=6
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Hours at the overtime multiplier.",
                        max_digits=6,
                    ),
                ),
                (
                    "sunday_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Hours at the Sunday multiplier.",
                        max_digits=6,
                    ),
                ),
                (
                    "public_holiday_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Hours worked on a public holiday.",
                        max_digits=6,
                    ),
                ),
                (
                    "night_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text=(
                            "Hours inside the night-work window. A tag on the buckets above, "
                            "not additive."
                        ),
                        max_digits=6,
                    ),
                ),
                (
                    "paid_hours_guaranteed",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="SD1 six-hour guarantee top-up.",
                        max_digits=6,
                    ),
                ),
                (
                    "days_worked_equivalent",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text=(
                            "1.000 for a full day, 0.500 for a half day - drives daily-rate "
                            "pay and leave accrual."
                        ),
                        max_digits=5,
                    ),
                ),
                ("is_standby", models.BooleanField(default=False, help_text="SD7 standby shift.")),
                (
                    "standby_hours_worked",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Actual work performed while on standby.",
                        max_digits=6,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("bulk_grid", "Bulk grid"),
                            ("import", "Import"),
                            ("self_service", "Self service"),
                            ("generated", "Generated"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("captured", "Captured"),
                            ("approved", "Approved"),
                            ("locked", "Locked"),
                        ],
                        db_index=True,
                        default="captured",
                        max_length=20,
                    ),
                ),
                (
                    "locked_by_payroll_run_id_ref",
                    models.BigIntegerField(
                        blank=True,
                        help_text=(
                            "Becomes a real FK to payroll_run in P7. Set when a run "
                            "finalises; blocks edits."
                        ),
                        null=True,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_days",
                        to="employees.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site worked - contract cleaning.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_days",
                        to="employers.workplace",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_day",
                "ordering": ["employee_id", "-work_date"],
            },
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(
                fields=["tenant", "work_date"], name="attendance__tenant__680e34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(
                fields=["employee", "work_date", "status"], name="attendance__employe_266580_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceday",
            index=models.Index(
                fields=["workplace", "work_date"], name="attendance__workpla_e4fa87_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.UniqueConstraint(
                fields=("employee", "work_date"), name="uniq_attendance_day_per_employee"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "day_type__in",
                        [
                            "ordinary",
                            "rest_day",
                            "sunday",
                            "public_holiday",
                            "leave",
                            "absent_unpaid",
                            "absent_paid",
                            "no_work_available",
                        ],
                    )
                ),
                name="attendance_day_day_type_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "ordinary_hours__lte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.Value(24), "-", models.F("overtime_hours")
                                ),
                                "-",
                                models.F("sunday_hours"),
                            ),
                            "-",
                            models.F("public_holiday_hours"),
                        ),
                    )
                ),
                name="attendance_day_hours_sum_under_24",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("night_hours__gte", 0),
                    ("ordinary_hours__gte", 0),
                    ("overtime_hours__gte", 0),
                    ("paid_hours_guaranteed__gte", 0),
                    ("public_holiday_hours__gte", 0),
                    ("standby_hours_worked__gte", 0),
                    ("sunday_hours__gte", 0),
                ),
                name="attendance_day_hours_are_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("day_type", "leave"), ("leave_application_id_ref__isnull", False)),
                    models.Q(
                        models.Q(("day_type", "leave"), _negated=True),
                        ("leave_application_id_ref__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="attendance_day_leave_needs_a_leave_application",
            ),
        ),
        migrations.RunSQL(enable_rls("attendance_day"), disable_rls("attendance_day")),
        migrations.RunSQL(LOCKED_ROW_FUNCTION, DROP_LOCKED_ROW_FUNCTION),
        migrations.RunSQL(
            no_update_when_locked("attendance_day"), drop_no_update_when_locked("attendance_day")
        ),
    ]
