# Generated by Django 5.2.17 on 2026-09-14 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """``timesheet_summary`` — P5 chunk 2. An ordinary ``TenantScopedModel``
    table, the plain ``enable_rls``. A cache with no lock of its own: it is
    recomputed, never hand-edited, so nothing here needs a trigger the way
    ``attendance_day``'s locked status does.
    """

    dependencies = [
        ("attendance", "0001_initial"),
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0008_employeeimportbatch_employee_created_by_import_batch_and_more"),
        ("payroll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_ordinary_hours",
                    models.DecimalField(decimal_places=3, default=0, max_digits=9),
                ),
                (
                    "total_overtime_hours",
                    models.DecimalField(decimal_places=3, default=0, max_digits=9),
                ),
                (
                    "total_sunday_hours",
                    models.DecimalField(decimal_places=3, default=0, max_digits=9),
                ),
                (
                    "total_public_holiday_hours",
                    models.DecimalField(decimal_places=3, default=0, max_digits=9),
                ),
                (
                    "total_night_hours",
                    models.DecimalField(decimal_places=3, default=0, max_digits=9),
                ),
                ("total_standby_shifts", models.SmallIntegerField(default=0)),
                (
                    "total_days_worked",
                    models.DecimalField(decimal_places=3, default=0, max_digits=7),
                ),
                (
                    "total_paid_leave_days",
                    models.DecimalField(decimal_places=3, default=0, max_digits=7),
                ),
                (
                    "total_unpaid_days",
                    models.DecimalField(decimal_places=3, default=0, max_digits=7),
                ),
                (
                    "total_public_holidays_not_worked",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Paid if they fall on an ordinary working day.",
                        max_digits=7,
                    ),
                ),
                ("computed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "is_stale",
                    models.BooleanField(
                        default=False, help_text="Set when an underlying attendance_day changes."
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_summaries",
                        to="employees.employee",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timesheet_summaries",
                        to="payroll.payperiod",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "timesheet_summary",
                "ordering": ["employee_id", "-pay_period_id"],
            },
        ),
        migrations.AddIndex(
            model_name="timesheetsummary",
            index=models.Index(fields=["tenant", "pay_period"], name="timesheet_s_tenant__356ebb_idx"),
        ),
        migrations.AddConstraint(
            model_name="timesheetsummary",
            constraint=models.UniqueConstraint(
                fields=("employee", "pay_period"), name="uniq_timesheet_summary_per_employee_period"
            ),
        ),
        migrations.RunSQL(enable_rls("timesheet_summary"), disable_rls("timesheet_summary")),
    ]
