# Generated by Django 5.2.17 on 2026-09-14 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core.db.rls import disable_rls, enable_rls


class Migration(migrations.Migration):
    """``attendance_import_batch`` — sheet 02 and sheet 03, P5 chunk 3 (D-155,
    D-156).

    An ordinary ``TenantScopedModel`` table, so the plain ``enable_rls`` — no
    shared rows, no system-row lock, no locked-status trigger of its own (the
    batch row itself is never frozen the way an ``attendance_day`` is; only
    the days it touches can be).

    ``prior_state`` is NOT in sheet 02 — see the model's own docstring and
    D-156: a reverse that only deleted would discard the employer's own
    earlier, legitimate capture, which is not this batch's to throw away.

    ``attendance_day.import_batch`` rides along in the same migration: sheet
    02 always had a place for it, chunk 1 deliberately left it out rather
    than ship a placeholder a week away from being replaced, and it cannot
    exist before this table does.
    """

    dependencies = [
        ("attendance", "0002_timesheetsummary"),
        ("core", "0006_fileobject_content_purged_at"),
        ("employers", "0004_payroll_component"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("row_count", models.IntegerField(default=0)),
                ("accepted_count", models.IntegerField(default=0)),
                ("rejected_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("validating", "Validating"),
                            ("preview", "Preview"),
                            ("applied", "Applied"),
                            ("reversed", "Reversed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "validation_report",
                    models.JSONField(
                        default=list,
                        help_text="Per-row errors and warnings. Never a full ID or bank number.",
                    ),
                ),
                (
                    "prior_state",
                    models.JSONField(
                        default=list,
                        help_text=(
                            "D-156. One entry per day this batch REPLACED: the employee id, "
                            "the work date, and every mutable attendance_day column's value "
                            "before the replace. Empty for a day the batch created outright "
                            "— reverse deletes those instead of restoring them."
                        ),
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_import_batches",
                        to="employers.employer",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "The uploaded spreadsheet. Content is purged once applied or "
                            "reversed (D-141)."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fileobject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_import_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="attendanceday",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text=(
                    "Set only by the bulk importer, and only for as long as that batch's "
                    "write stands. Reverse restores a replaced day to what it held before "
                    "and clears this back to whatever it named then (D-155)."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="days",
                to="attendance.attendanceimportbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceimportbatch",
            index=models.Index(fields=["tenant", "status"], name="attendance__tenant__252f12_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceimportbatch",
            index=models.Index(
                fields=["period_start", "period_end"], name="attendance__period__bdc89e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceimportbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["uploaded", "validating", "preview", "applied", "reversed", "failed"],
                    )
                ),
                name="attendance_import_batch_status_is_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceimportbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="attendance_import_batch_period_end_after_start",
            ),
        ),
        migrations.RunSQL(
            enable_rls("attendance_import_batch"), disable_rls("attendance_import_batch")
        ),
    ]
