# Generated by Django 5.2.17 on 2026-09-15 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """P6 chunk 2, task 4: the placeholder becomes real.

    ``leave_application_id_ref`` (a ``BigIntegerField``, since P5) is
    replaced by a real FK to ``leave.LeaveApplication``, which now exists.
    Sheet 03's CHECK travels across unchanged in substance, just against the
    real column. No data migration: a ``day_type='leave'`` row was
    impossible to create before this chunk (the CHECK forbade it against
    the placeholder), so the old column is empty everywhere.
    """

    dependencies = [
        ("attendance", "0003_attendance_import_batch_and_import_batch_fk"),
        ("core", "0006_fileobject_content_purged_at"),
        ("employees", "0008_employeeimportbatch_employee_created_by_import_batch_and_more"),
        ("employers", "0004_payroll_component"),
        ("leave", "0008_leave_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendanceday",
            name="attendance_day_leave_needs_a_leave_application",
        ),
        migrations.RemoveField(
            model_name="attendanceday",
            name="leave_application_id_ref",
        ),
        migrations.AddField(
            model_name="attendanceday",
            name="leave_application",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only when day_type='leave', by leave/authorisation.py's approve().",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_days",
                to="leave.leaveapplication",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("day_type", "leave"), ("leave_application__isnull", False)),
                    models.Q(
                        models.Q(("day_type", "leave"), _negated=True),
                        ("leave_application__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="attendance_day_leave_needs_a_leave_application",
            ),
        ),
    ]
